---
permalink: config-linux/fc-install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Linux Unified Host Utilities, express linux configuration, software configuration, linux host, 
summary: Installare Linux Unified host Utilities quando si utilizza FC. 
---
= Installare e configurare Linux Unified host Utilities
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli strumenti delle utility host unificate di Linux consentono di gestire lo storage NetApp, incluse policy di failover e percorsi fisici.

.Fasi
. Utilizzare https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^] Per determinare la versione appropriata di Unified host Utilities da installare.
+
Le versioni sono elencate in una colonna all'interno di ciascuna configurazione supportata.

. Scaricare le Unified host Utilities da https://mysupport.netapp.com/site/["Supporto NetApp"^].
+

NOTE: In alternativa, è possibile utilizzare l'utility SMdevices di SANtricity per eseguire le stesse funzioni dello strumento Unified host Utility. L'utility SMdevices è inclusa nel pacchetto SMutils. Il pacchetto SMutils è una raccolta di utility per verificare ciò che l'host vede dall'array di storage. È incluso nell'installazione del software SANtricity.


