---
permalink: config-linux/iser-ib-access-sam-setup-wizard-task.html 
sidebar: sidebar 
keywords: access System Manager Linux, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Per configurare lo storage array, utilizzare la procedura guidata di installazione di Gestione sistema di SANtricity. 
---
= Configurazione dello storage con SANtricity System Manager - Linux (iSER over InfiniBand)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per configurare lo storage array, è possibile utilizzare la procedura di installazione guidata in Gestore di sistema di SANtricity.

Gestore di sistema di SANtricity è un'interfaccia basata su web integrata in ogni controller. Per accedere all'interfaccia utente, puntare un browser verso l'indirizzo IP del controller. L'installazione guidata consente di iniziare a configurare il sistema.

.Prima di iniziare
Assicurarsi di disporre di quanto segue:

* Gestione fuori banda.
* Stazione di gestione per l'accesso a Gestore di sistema di SANtricity che include uno dei seguenti browser:
+
|===
| Browser | Versione minima 


 a| 
Google Chrome
 a| 
89



 a| 
Microsoft Edge
 a| 
90



 a| 
Mozilla Firefox
 a| 
80



 a| 
Safari
 a| 
14

|===


.A proposito di questa attività
La procedura guidata viene riavviata automaticamente quando si apre System Manager o si aggiorna il browser e viene soddisfatta almeno una delle seguenti condizioni:

* Non vengono rilevati pool e gruppi di volumi.
* Nessun carico di lavoro rilevato.
* Nessuna notifica configurata.


.Fasi
. Dal browser, immettere il seguente URL: `+https://<DomainNameOrIPAddress>+`
+
`IPAddress` è l'indirizzo di uno dei controller degli array di storage.

+
La prima volta che si apre Gestore di sistema di SANtricity su un array non configurato, viene visualizzato il prompt Set Administrator Password (Imposta password amministratore). La gestione degli accessi basata sui ruoli configura quattro ruoli locali: amministrazione, supporto, sicurezza e monitoraggio. Gli ultimi tre ruoli hanno password casuali che non possono essere indovinate. Dopo aver impostato una password per il ruolo di amministratore, è possibile modificare tutte le password utilizzando le credenziali di amministratore. Per ulteriori informazioni sui quattro ruoli utente locali, consultare la guida in linea disponibile nell'interfaccia utente di Gestore di sistema di SANtricity.

. Immettere la password di System Manager per il ruolo di amministratore nei campi Set Administrator Password (Imposta password amministratore) e Confirm Password (Conferma password), quindi fare clic su *Set Password* (Imposta password).
+
L'installazione guidata viene avviata se non sono configurati pool, gruppi di volumi, carichi di lavoro o notifiche.

. Utilizzare l'installazione guidata per eseguire le seguenti operazioni:
+
** *Verifica dell'hardware (controller e dischi)* -- verifica del numero di controller e dischi nell'array di storage. Assegnare un nome all'array.
** *Verifica di host e sistemi operativi* -- verifica dei tipi di host e sistemi operativi a cui lo storage array può accedere.
** *Accept Pools* -- accettare la configurazione del pool consigliata per il metodo di installazione rapida. Un pool è un gruppo logico di dischi.
** *Configura avvisi* -- consente a System Manager di ricevere notifiche automatiche quando si verifica un problema con lo storage array.
** *Enable AutoSupport* -- monitora automaticamente lo stato dello storage array e invia le spedizioni al supporto tecnico.


. Se non hai ancora creato un volume, creane uno dal menu:Storage[Volumes > Create > Volume].
+
Per ulteriori informazioni, consultare la guida in linea di Gestore di sistema di SANtricity.


