---
permalink: config-linux/iser-ib-configure-network-connections-task.html 
sidebar: sidebar 
keywords: configure network connection, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Se la configurazione utilizza il protocollo iSER su Infiniband, eseguire la procedura descritta in questa sezione. 
---
= Configurare le connessioni di rete
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se la configurazione utilizza il protocollo iSER su InfiniBand, eseguire la procedura descritta in questa sezione per configurare le connessioni di rete.

.Fasi
. Da System Manager, andare a menu:Impostazioni[sistema > Configura iSER su porte Infiniband]. Per ulteriori informazioni, consultare la guida in linea di System Manager.
+
Inserire gli indirizzi iSCSI dell'array nella stessa subnet delle porte host che verranno utilizzate per creare sessioni iSCSI. Per gli indirizzi, consultare il xref:iser-ib-worksheet-concept.adoc[Foglio di lavoro di iser].

. Registrare l'IQN.
+
Queste informazioni potrebbero essere necessarie quando si creano sessioni iSER da sistemi operativi che non supportano il rilevamento delle destinazioni di invio. Inserire queste informazioni nel campo xref:iser-ib-worksheet-concept.adoc[Foglio di lavoro di iser].


