---
permalink: config-linux/nvme-fc-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Configurare l"host per eseguire il failover.' 
---
= Configurare il failover sull'host in e-Series - Linux (NVMe over FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per fornire un percorso ridondante all'array di storage, è possibile configurare l'host per eseguire il failover.

.Prima di iniziare
È necessario installare i pacchetti richiesti sul sistema.

* Per gli host Red Hat (RHEL), verificare che i pacchetti siano installati eseguendo `rpm -q device-mapper-multipath`
* Per gli host SLES, verificare che i pacchetti siano installati eseguendo `rpm -q multipath-tools`


 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Fibre Channel. RHEL 8, RHEL 9, and SLES 15 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.


== Abilita Device Mapper Multipath (DMMP) per SLES 12

Per impostazione predefinita, DM-MP è disabilitato in SLES. Completare la procedura seguente per abilitare i componenti DM-MP nell'host.

.Fasi
. Aggiungere la voce NVMe e-Series Device alla sezione devices del file /etc/multipath.conf, come mostrato nell'esempio seguente:
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Configurare `multipathd` per iniziare all'avvio del sistema.
+
[listing]
----
# systemctl enable multipathd
----
. Inizio `multipathd` se non è in esecuzione.
+
[listing]
----
# systemctl start multipathd
----
. Verificare lo stato di `multipathd` per assicurarsi che sia attivo e in esecuzione:
+
[listing]
----
# systemctl status multipathd
----




== Impostare NVMe Multipathing nativo per RHEL 8

.A proposito di questa attività
NVMe Multipathing nativo è disattivato per impostazione predefinita in RHEL 8 e deve essere attivato seguendo la procedura riportata di seguito.

.Fasi
. Setup (Configurazione) `modprobe` Regola per attivare NVMe Multipathing nativo.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Remake `initramfs` con il nuovo parametro modprobe.
+
[listing]
----
# dracut -f
----
. Riavviare il server per attivarlo con NVMe Multipathing nativo attivato
+
[listing]
----
# reboot
----
. Verificare che il multipathing NVMe nativo sia stato attivato dopo l'avvio del backup dell'host.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Se l'output del comando è `N`, Quindi NVMe Multipathing nativo è ancora disattivato.
.. Se l'output del comando è `Y`, Quindi viene attivato NVMe Multipathing nativo e tutti i dispositivi NVMe rilevati lo utilizzeranno.





NOTE: Per RHEL 9 e SLES 15, il multipathing NVMe nativo è attivato per impostazione predefinita e non è richiesta alcuna configurazione aggiuntiva.
