---
permalink: config-linux/nvme-ib-access-physical-targets-concept.html 
sidebar: sidebar 
keywords: NVMe volume physical, SLES 15, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'È possibile configurare l"i/o diretto alla destinazione del dispositivo in base alla versione di SLES (versione di SUSE Linux).' 
---
= Accesso ai volumi NVMe per destinazioni fisiche di dispositivi NVMe in e-Series - Linux (NVMe over InfiniBand)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare l'i/o diretto alla destinazione del dispositivo in base al sistema operativo in uso (e al metodo multipathing interno).

Per RHEL 8, RHEL 9 e SLES 15, l'i/o viene indirizzato alle destinazioni fisiche del dispositivo NVMe dall'host Linux. Una soluzione NVMe multipathing nativa gestisce i percorsi fisici sottostanti il singolo dispositivo fisico apparente visualizzato dall'host.



== I dispositivi NVMe fisici sono destinazioni di i/O.

È consigliabile eseguire i/o ai collegamenti in `/dev/disk/by-id/nvme-eui.[uuid#]` piuttosto che direttamente al percorso fisico del dispositivo nvme `/dev/nvme[subsys#]n[id#]`. Il collegamento tra queste due posizioni può essere trovato usando il seguente comando:

[listing]
----
# ls /dev/disk/by-id/ -l
lrwxrwxrwx 1 root root 13 Oct 18 15:14 nvme-eui.0000320f5cad32cf00a0980000af4112 -> ../../nvme0n1
----
I/o eseguito a. `/dev/disk/by-id/nvme-eui.[uuid#]` verrà passata direttamente `/dev/nvme[subsys#]n[id#]` Che ha tutti i percorsi virtualizzati sotto l'IT utilizzando la soluzione di multipathing NVMe nativa.

Puoi visualizzare i tuoi percorsi eseguendo:

[listing]
----
# nvme list-subsys
----
Output di esempio:

[listing]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:5700.600a098000a522500000000589aa8a6
\
+- nvme0 rdma traddr=192.4.21.131 trsvcid=4420 live
+- nvme1 rdma traddr=192.4.22.141 trsvcid=4420 live
----
Se si specifica un dispositivo nvme fisico quando si utilizza il comando 'nvme list-subsys', vengono fornite ulteriori informazioni sui percorsi per lo spazio dei nomi:

[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:5700.600a098000af44620000000058d5dd96
\
 +- nvme0 rdma traddr=192.168.130.101 trsvcid=4420 live non-optimized
 +- nvme1 rdma traddr=192.168.131.101 trsvcid=4420 live non-optimized
 +- nvme2 rdma traddr=192.168.130.102 trsvcid=4420 live optimized
 +- nvme3 rdma traddr=192.168.131.102 trsvcid=4420 live optimized
----
Sono inoltre presenti collegamenti ai comandi multipath per consentire di visualizzare le informazioni sul percorso per il failover nativo attraverso di essi:

[listing]
----
#multipath -ll
----

NOTE: Per visualizzare le informazioni sul percorso, impostare quanto segue in /etc/multipath.conf:

[listing]
----

defaults {
        enable_foreign nvme
}
----
Output di esempio:

[listing]
----
eui.0000a0335c05d57a00a0980000a5229d [nvme]:nvme0n9 NVMe,Netapp E-Series,08520001
size=4194304 features='n/a' hwhandler='ANA' wp=rw
|-+- policy='n/a' prio=50 status=optimized
| `- 0:0:1 nvme0c0n1 0:0 n/a optimized    live
`-+- policy='n/a' prio-10 status=non-optimized
`- 0:1:1 nvme0c1n1 0:0 n/a non-optimized    live
----