---
permalink: config-linux/nvme-ib-setup-host-side-task.html 
sidebar: sidebar 
keywords: configure Linux host, express linux configuration, linux host, 
summary: 'La configurazione di un iniziatore NVMe in un ambiente InfiniBand include l"installazione e la configurazione dei pacchetti infiniband, nvme-cli e rdma, la configurazione degli indirizzi IP dell"iniziatore e l"impostazione del layer NVMe-of sull"host.' 
---
= Impostare NVMe su InfiniBand sul lato host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configurazione di un iniziatore NVMe in un ambiente InfiniBand include l'installazione e la configurazione dei pacchetti infiniband, nvme-cli e rdma, la configurazione degli indirizzi IP dell'iniziatore e l'impostazione del layer NVMe-of sull'host.

.Di cosa hai bisogno
È necessario utilizzare il sistema operativo RHEL 7, RHEL 8, RHEL 9, SUSE Linux Enterprise Server 12 o 15 Service Pack più recente. Vedere https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^] per un elenco completo dei requisiti più recenti.

.Fasi
. Installare i pacchetti rdma, nvme-cli e infiniband:
+
*SLES 12 o SLES 15*

+
[listing]
----

# zypper install infiniband-diags
# zypper install rdma-core
# zypper install nvme-cli
----
+
*RHEL 7, RHEL 8 O RHEL 9*

+
[listing]
----

# yum install infiniband-diags
# yum install rdma-core
# yum install nvme-cli
----
. Per RHEL 8 o RHEL 9, installare gli script di rete:
+
*RHEL 8*

+
[listing]
----
# yum install network-scripts
----
+
*RHEL 9*

+
[listing]
----
# yum install NetworkManager-initscripts-updown
----
. Per RHEL 7, attivare `ipoib`. Modificare il file /etc/rdma/rdma.conf e modificare la voce per il caricamento `ipoib`:
+
[listing]
----
IPOIB_LOAD=yes
----
. Ottenere l'NQN host, che verrà utilizzato per configurare l'host in un array.
+
[listing]
----
# cat /etc/nvme/hostnqn
----
. Verificare che entrambi i collegamenti delle porte IB siano attivi e che lo stato sia attivo:
+
[listing]
----
# ibstat
----
+
[listing]
----
CA 'mlx4_0'
        CA type: MT4099
        Number of ports: 2
        Firmware version: 2.40.7000
        Hardware version: 1
        Node GUID: 0x0002c90300317850
        System image GUID: 0x0002c90300317853
        Port 1:
                State: Active
                Physical state: LinkUp
                Rate: 40
                Base lid: 4
                LMC: 0
                SM lid: 4
                Capability mask: 0x0259486a
                Port GUID: 0x0002c90300317851
                Link layer: InfiniBand
        Port 2:
                State: Active
                Physical state: LinkUp
                Rate: 56
                Base lid: 5
                LMC: 0
                SM lid: 4
                Capability mask: 0x0259486a
                Port GUID: 0x0002c90300317852
                Link layer: InfiniBand
----
. Impostare gli indirizzi IP IPv4 sulle porte ib.
+
*SLES 12 o SLES 15*

+
Creare il file /etc/sysconfig/network/ifcfg-ib0 con il seguente contenuto.

+
[listing]
----

BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='10.10.10.100/24'
IPOIB_MODE='connected'
MTU='65520'
NAME=
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
Quindi, creare il file /etc/sysconfig/network/ifcfg-ib1:

+
[listing]
----

BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='11.11.11.100/24'
IPOIB_MODE='connected'
MTU='65520'
NAME=
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
*RHEL 7 o RHEL 8*

+
Creare il file /etc/sysconfig/network-scripts/ifcfg-ib0 con il seguente contenuto.

+
[listing]
----

CONNECTED_MODE=no
TYPE=InfiniBand
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=static
IPADDR='10.10.10.100/24'
DEFROUTE=no
IPV4=FAILURE_FATAL=yes
IPV6INIT=no
NAME=ib0
ONBOOT=yes
----
+
Quindi, creare il file /etc/sysconfig/network-scripts/ifcfg-ib1:

+
[listing]
----

CONNECTED_MODE=no
TYPE=InfiniBand
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=static
IPADDR='11.11.11.100/24'
DEFROUTE=no
IPV4=FAILURE_FATAL=yes
IPV6INIT=no
NAME=ib1
ONBOOT=yes
----
+
*RHEL 9*

+
Utilizzare `nmtui` per attivare e modificare una connessione. Di seguito è riportato un file di esempio `/etc/NetworkManager/system-connections/ib0.nmconnection` il tool genera:

+
[listing]
----
[connection]
id=ib0
uuid=<unique uuid>
type=infiniband
interface-name=ib0

[infiniband]
mtu=4200

[ipv4]
address1=10.10.10.100/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
+
Di seguito è riportato un file di esempio `/etc/NetworkManager/system-connections/ib1.nmconnection` il tool genera:

+
[listing]
----
[connection]
id=ib1
uuid=<unique uuid>
type=infiniband
interface-name=ib1

[infiniband]
mtu=4200

[ipv4]
address1=11.11.11.100/24'
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
. Attivare il `ib` interfaccia:
+
[listing]
----

# ifup ib0
# ifup ib1
----
. Verificare gli indirizzi IP utilizzati per la connessione all'array. Eseguire questo comando per entrambi `ib0` e. `ib1`:
+
[listing]
----

# ip addr show ib0
# ip addr show ib1
----
+
Come illustrato nell'esempio riportato di seguito, l'indirizzo IP di `ib0` è `10.10.10.255`.

+
[listing]
----
10: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc pfifo_fast state UP group default qlen 256
    link/infiniband 80:00:02:08:fe:80:00:00:00:00:00:00:00:02:c9:03:00:31:78:51 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 10.10.10.255 brd 10.10.10.255 scope global ib0
       valid_lft forever preferred_lft forever
    inet6 fe80::202:c903:31:7851/64 scope link
       valid_lft forever preferred_lft forever
----
+
Come illustrato nell'esempio riportato di seguito, l'indirizzo IP di `ib1` è `11.11.11.255`.

+
[listing]
----
10: ib1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc pfifo_fast state UP group default qlen 256
    link/infiniband 80:00:02:08:fe:80:00:00:00:00:00:00:00:02:c9:03:00:31:78:51 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 11.11.11.255 brd 11.11.11.255 scope global ib0
       valid_lft forever preferred_lft forever
    inet6 fe80::202:c903:31:7851/64 scope link
       valid_lft forever preferred_lft forever
----
. Impostare il livello NVMe-of sull'host. Creare i seguenti file in /etc/modules-load.d/ per caricare `nvme-rdma` kernel e assicurarsi che il modulo kernel sia sempre attivo, anche dopo un riavvio:
+
[listing]
----

# cat /etc/modules-load.d/nvme-rdma.conf
  nvme-rdma
----
+
Per verificare `nvme-rdma` kernel module è stato caricato, eseguire questo comando:

+
[listing]
----

# lsmod | grep nvme
nvme_rdma              36864  0
nvme_fabrics           24576  1 nvme_rdma
nvme_core             114688  5 nvme_rdma,nvme_fabrics
rdma_cm               114688  7 rpcrdma,ib_srpt,ib_srp,nvme_rdma,ib_iser,ib_isert,rdma_ucm
ib_core               393216  15 rdma_cm,ib_ipoib,rpcrdma,ib_srpt,ib_srp,nvme_rdma,iw_cm,ib_iser,ib_umad,ib_isert,rdma_ucm,ib_uverbs,mlx5_ib,qedr,ib_cm
t10_pi                 16384  2 sd_mod,nvme_core
----

