---
permalink: config-linux/nvme-ib-determine-host-port-guids-task.html 
sidebar: sidebar 
keywords: host port GUIDs, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Determinare i GUID della porta host. 
---
= Determinare i GUID della porta host ed effettuare le impostazioni consigliate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il pacchetto infiniband-DIAGS include comandi per visualizzare il GUID (Globally Unique ID) di ciascuna porta InfiniBand (IB). La maggior parte delle distribuzioni Linux con OFED/RDMA supportate tramite i pacchetti inclusi dispone anche del pacchetto infiniband-Diags, che include comandi per visualizzare informazioni sull'adattatore del canale host (HCA).

.Fasi
. Installare `infiniband-diags` che utilizza i comandi di gestione dei pacchetti del sistema operativo.
. Eseguire `ibstat` per visualizzare le informazioni sulla porta.
. Registrare i GUID dell'iniziatore su xref:nvme-ib-worksheet-concept.adoc[Foglio di lavoro SRP].
. Selezionare le impostazioni appropriate nell'utility HBA.
+
Le impostazioni appropriate per la configurazione sono elencate nella colonna Note di https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].


