---
permalink: config-linux/overview-concept.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Verifica dei requisiti per l"utilizzo del metodo Express per la configurazione di un array e-Series e di un host Linux.' 
---
= Presupposti (e-Series e Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il metodo Linux Express si basa sui seguenti presupposti:

|===
| Componente | Presupposti 


 a| 
Hardware
 a| 
* Per installare l'hardware, sono state utilizzate le istruzioni di installazione e configurazione fornite con gli shelf dei controller.
* Sono stati collegati i cavi tra gli shelf di dischi opzionali e i controller.
* Il sistema storage è alimentato.
* Hai installato tutto l'altro hardware (ad esempio, stazione di gestione, switch) e hai effettuato le connessioni necessarie.
* Se si utilizza NVMe su Infiniband, NVMe su RoCE o NVMe su Fibre Channel, ciascun controller EF300, EF600, EF570 o E5700 contiene almeno 32 GB di RAM.




 a| 
Host
 a| 
* È stata stabilita una connessione tra il sistema storage e l'host dati.
* Il sistema operativo host è stato installato.
* Non stai utilizzando Linux come guest virtualizzato.
* Non si sta configurando l'host dati (i/o collegato) per l'avvio da SAN.
* Sono stati installati gli aggiornamenti del sistema operativo elencati nella sezione https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].




 a| 
Stazione di gestione dello storage
 a| 
* Si utilizza una rete di gestione a 1 Gbps o più veloce.
* Si sta utilizzando una stazione separata per la gestione piuttosto che l'host dei dati (i/o collegato).
* Si sta utilizzando la gestione out-of-band, in cui una stazione di gestione dello storage invia comandi al sistema di storage attraverso le connessioni Ethernet al controller.
* La stazione di gestione è stata collegata alla stessa subnet delle porte di gestione dello storage.




 a| 
Indirizzamento IP
 a| 
* È stato installato e configurato un server DHCP.
* È stata ancora stabilita una connessione Ethernet tra la stazione di gestione e il sistema di storage.




 a| 
Provisioning dello storage
 a| 
* Non verranno utilizzati volumi condivisi.
* Verranno creati pool anziché gruppi di volumi.




 a| 
Protocollo: FC
 a| 
* Sono state effettuate tutte le connessioni FC sul lato host e lo zoning dello switch attivato.
* Stai utilizzando HBA e switch FC supportati da NetApp.
* Si stanno utilizzando le versioni del driver e del firmware dell'HBA FC elencate nella https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].




 a| 
Protocollo: ISCSI
 a| 
* Si utilizzano switch Ethernet in grado di trasportare il traffico iSCSI.
* Gli switch Ethernet sono stati configurati in base alle raccomandazioni del vendor per iSCSI.




 a| 
Protocollo: SAS
 a| 
* Stai utilizzando HBA SAS supportati da NetApp.
* Si stanno utilizzando le versioni del driver e del firmware dell'HBA SAS elencate nella https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].




 a| 
Protocollo: Er su InfiniBand
 a| 
* Si sta utilizzando un fabric InfiniBand.
* Si stanno utilizzando le versioni del driver e del firmware dell'HBA IB-iSER elencate nella https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].




 a| 
Protocollo: SRP su InfiniBand
 a| 
* Si sta utilizzando un fabric InfiniBand.
* Si stanno utilizzando le versioni del driver e del firmware IB-SRP elencate nella https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].




 a| 
Protocollo: NVMe su InfiniBand
 a| 
* Sono state ricevute le schede di interfaccia host 100G o 200G in un sistema storage EF300, EF600, EF570 o E5700 preconfigurato con il protocollo NVMe over InfiniBand oppure i controller sono stati ordinati con porte IB standard e devono essere convertiti in porte NVMe-of.
* Si sta utilizzando un fabric InfiniBand.
* Si stanno utilizzando le versioni del driver e del firmware NVMe/IB elencate nella https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].




 a| 
Protocollo: NVMe su RoCE
 a| 
* Sono state ricevute le schede di interfaccia host 100G o 200G in un sistema storage EF300, EF600, EF570 o E5700 preconfigurato con il protocollo NVMe over RoCE oppure i controller sono stati ordinati con porte IB standard e devono essere convertiti in porte NVMe-of.
* Si stanno utilizzando le versioni del driver e del firmware NVMe/RoCE elencate nella https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].




 a| 
Protocollo: NVMe su Fibre Channel
 a| 
* Le schede di interfaccia host 32G sono state ricevute in un sistema storage EF300, EF600, EF570 o E5700 preconfigurato con il protocollo NVMe over Fibre Channel oppure i controller sono stati ordinati con porte FC standard e devono essere convertiti in porte NVMe-of.
* Si utilizzano driver NVMe/FC e versioni firmware come indicato nella https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].


|===

NOTE: Queste istruzioni del metodo espresso includono esempi per SUSE Linux Enterprise Server (SLES) e per Red Hat Enterprise Linux (RHEL).
