---
permalink: config-linux/sas-install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Linux Unified Host Utilities, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: Linux Unified host Utilities 7.1 include tool per gestire lo storage NetApp, incluse policy di failover e percorsi fisici. 
---
= Installare e configurare Linux Unified host Utilities
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli strumenti delle utility host unificate di Linux consentono di gestire lo storage NetApp, incluse policy di failover e percorsi fisici.

.Fasi
. Utilizzare https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^] Per determinare la versione appropriata di Unified host Utilities da installare.
+
Le versioni sono elencate in una colonna all'interno di ciascuna configurazione supportata.

. Scaricare le Unified host Utilities da https://mysupport.netapp.com/site/["Supporto NetApp"^].
+

NOTE: In alternativa, è possibile utilizzare il comando SMcli `-identifyDevices` Per eseguire le stesse funzioni dello strumento Unified host Utility. SMcli è incluso nel sistema operativo SANtricity e può essere scaricato tramite il Gestore di sistema di SANtricity. Per ulteriori informazioni su come scaricare SMcli tramite il Gestore di sistema di SANtricity, fare riferimento alla https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Scaricare l'argomento dell'interfaccia a riga di comando (CLI) nella Guida in linea di SANtricity System Manager"^].


