---
permalink: config-linux/sas-determine-sas-host-ids-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Per il protocollo SAS, individuare gli indirizzi SAS utilizzando l"utility HBA, quindi utilizzare il BIOS HBA per definire le impostazioni di configurazione appropriate.' 
---
= Determinare gli identificatori host SAS - Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il protocollo SAS, individuare gli indirizzi SAS utilizzando l'utility HBA, quindi utilizzare il BIOS HBA per definire le impostazioni di configurazione appropriate.

Prima di iniziare questa procedura, consultare le seguenti linee guida per le utility HBA:

* La maggior parte dei vendor HBA offre un'utility HBA. A seconda del sistema operativo host e della CPU, utilizzare l'utility LSI-sas2flash(6G) o sas3flash(12G).
* Le porte i/o host potrebbero essere registrate automaticamente se è installato l'agente di contesto host.


.Fasi
. Scaricare l'utility HBA dal sito Web del vendor HBA.
. Installare l'utility.
. Utilizzare il BIOS HBA per selezionare le impostazioni appropriate per la configurazione.
+
Vedere la colonna Note di https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^] per consigli.


