---
permalink: config-linux/srp-ib-install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Unified Host Utilities, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Linux Unified host Utilities 7.1 include tool per gestire lo storage NetApp, incluse policy di failover e percorsi fisici. 
---
= Installare e configurare le utility host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il pacchetto Linux Unified host Utilities include strumenti per la gestione dello storage NetApp, tra cui policy di failover e percorsi fisici.

.Fasi
. Utilizzare https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^] Per determinare la versione appropriata di Unified host Utilities da installare.
+
Le versioni sono elencate in una colonna all'interno di ciascuna configurazione supportata.

. Scaricare le Unified host Utilities da https://mysupport.netapp.com/site/["Supporto NetApp"^].
+

NOTE: In alternativa, è possibile utilizzare l'utility SMdevices di SANtricity per eseguire le stesse funzioni dello strumento Unified host Utility. L'utility SMdevices è inclusa nel pacchetto SMutils. Il pacchetto SMutils è una raccolta di utility per verificare ciò che l'host vede dall'array di storage. È incluso nell'installazione del software SANtricity.


