---
sidebar: sidebar 
permalink: rackmount-hardware.html 
keywords: rackmount, rack-mount, install in rack, rails 
summary: 'Montare l"hardware in rack.' 
---
= Hardware montato su rack (e-Series)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilizzare i collegamenti riportati di seguito per accedere alla documentazione che descrive come installare l'hardware per il montaggio su rack.



== Guide di supporto regolabili

Accesso https://mysupport.netapp.com/ecm/ecm_download_file/ECMP1652045["Installazione delle guide di supporto regolabili"^] per l'installazione di un vassoio del disco controller o di un vassoio del disco spedito separatamente (non già installato nel cabinet). Questa procedura si applica ai seguenti vassoi 2U (9 cm o 3.5 pollici):

* DE1600 o DE5600
* E2612 o E2624
* E5412, E5424, E5512 O E5524




== Rack a due montanti -- 2U

Accesso https://mysupport.netapp.com/ecm/ecm_download_file/ECMM1280302["Installazione dell'apparecchiatura 2U in un rack a due montanti"^].



== Rack o cabinet a quattro montanti -- 2U

Accesso https://mysupport.netapp.com/ecm/ecm_download_file/ECMLP2484194["Installazione di un enclosure 2U da 12 dischi in un rack o cabinet a quattro montanti"^].



== Rack a quattro montanti - SuperRail

Accesso https://docs.netapp.com/us-en/ontap-systems/platform-supplemental/superrail-install.html["Installazione di SuperRail in un rack a quattro montanti (shelf DE224C/DE460C)"^].
