---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: Nuove funzionalità di SANtricity OS. 
---
= Novità di SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La seguente tabella descrive le nuove funzionalità di SANtricity OS 11.8 per la gestione integrata dei controller EF300, EF600, E2800/EF280 e E5700/EF570.



== Nuove funzioni della versione 11.80.1

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
`-identifyDevices` parametro
 a| 
Un nuovo `-identifyDevices` Il parametro è ora disponibile in SMcli. Questo nuovo parametro consente di cercare tutti i dispositivi a blocchi nativi SCSI associati agli array di archiviazione. Per ulteriori informazioni, vedere il link: Parametri della riga di comando di https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-Devices[Downloadable SMcli^].



 a| 
Statistiche del kernel Ethernet
 a| 
Una nuova opzione Ethernet kernel Statistics è ora disponibile nella pagina View iSCSI Statistics Packages (Visualizza pacchetti statistiche iSCSI) in System Manager. Questa nuova opzione consente di visualizzare le statistiche per i driver del kernel della piattaforma del dispositivo iSCSI. Per ulteriori informazioni, vedere il link: https://docs.netapp.com/us-en/e-series-santricity/sm-support/view-iscsi-statistics-packages-support.html[View iSCSI Statistics Packages^].



 a| 
Miglioramento del filtraggio delle unità non assegnate e abilitate per la protezione in System Manager
 a| 
System Manager ora filtra le unità abilitate non assegnate e protette quando si selezionano le unità manuali. Pertanto, il numero di selezioni delle unità di System Manager corrisponde ora all'elenco di candidati per la selezione automatica delle unità presente nella CLI e nell'API REST. Un'icona univoca e il testo del passaggio del mouse vengono ora applicati anche alle unità abilitate non assegnate e protette in System Manager.



 a| 
Aggiunta la capacità di bloccare gli indirizzi IP tramite l'endpoint REST API
 a| 
Gli utenti possono ora bloccare indirizzi IP specifici tramite l'endpoint Impostazioni (`/devmgr/v2/settings`). Una volta configurato tramite l'endpoint Impostazioni, solo gli indirizzi IP specificati tramite una whitelist possono comunicare con il dispositivo di archiviazione. Questa nuova funzione supporta gli elenchi di indirizzi IPv4 e IPv6.



 a| 
Plug-in vCenter Storage
 a| 
Il plug-in vCenter Storage è stato aggiornato per verificarne la compatibilità con la release e-Series 11.80.1.



 a| 
Proxy dei servizi Web
 a| 
Web Services Proxy è stato aggiornato alla versione 6,1 per la compatibilità con la versione 11.80.1 di e-Series.

|===


== Nuove funzionalità della versione 11.80

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Enhanced Volume Parity Scan (scansione parity volume avanzata)
 a| 
La scansione della parità del volume può ora essere avviata come processo in background tramite l'API REST o tramite CLI. La scansione di parità risultante viene eseguita in background per tutto il tempo necessario per completare l'operazione di scansione. Le operazioni di scansione sopravvivono ai riavvii del controller e alle operazioni di failover.



 a| 
Supporto SAML per Unified Manager
 a| 
Unified Manager ora supporta SAML (Security Assertion Markup Language). Una volta abilitato SAML per Unified Manager, gli utenti devono utilizzare l'autenticazione a più fattori rispetto al provider di identità per interagire con l'interfaccia utente. Una volta abilitato SAML su Unified Manager, l'API REST non può essere utilizzata senza passare attraverso IdP per autenticare le richieste.



 a| 
Funzione di configurazione automatica
 a| 
Ora supporta la possibilità di impostare il parametro delle dimensioni del blocco del volume da utilizzare con la funzione di configurazione automatica per la configurazione iniziale dell'array. Questa funzione è disponibile nella CLI solo come parametro "blocksize".



 a| 
Firma crittografica del firmware del controller
 a| 
Il firmware del controller è firmato crittograficamente. Le firme vengono controllate durante il download iniziale e ad ogni avvio del controller. Nessun impatto previsto per l'utente finale. Le firme sono supportate da un certificato Extended Validation emesso dalla CA.



 a| 
Firma crittografica del firmware del disco
 a| 
Il firmware del disco è firmato crittograficamente. Le firme vengono controllate durante il download iniziale e supportate da un certificato Extended Validation emesso dalla CA. Il contenuto del firmware del disco viene ora fornito come file ZIP, che contiene il firmware precedente non firmato e il nuovo firmware firmato. L'utente deve scegliere il file appropriato in base alla versione di rilascio del codice in esecuzione sul sistema di destinazione.



 a| 
Gestione server chiavi esterne - dimensione chiave certificato
 a| 
La nuova chiave di certificato predefinita è di 3072 bit (da 2048). Sono supportate dimensioni delle chiavi fino a 4096 bit. Un bit NVSRAM deve essere modificato per supportare le dimensioni delle chiavi non predefinite.

I valori di selezione delle dimensioni chiave sono i seguenti:

* VALORE PREDEFINITO = 0
* LUNGHEZZA 2048 = 1
* LUNGHEZZA 3072 = 2
* LUNGHEZZA 4096 = 3


Per modificare la dimensione della chiave in 4096 tramite SMcli:

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

Interrogare le dimensioni della chiave:

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
Miglioramenti dei pool di dischi
 a| 
I pool di dischi creati con i controller che eseguono la versione 11,80 o superiore saranno _pool versione 1_ anziché _pool versione 0_. Un'operazione di downgrade è limitata quando esiste un pool di dischi _versione 1_.

La versione di un pool di dischi può essere identificata nel profilo dell'array di storage.



 a| 
System Manager e Unified Manager non verranno lanciati a meno che non vengano soddisfatti i requisiti minimi del browser
 a| 
È necessaria una versione minima del browser prima dell'avvio di System Manager o di Unified Manager.

Di seguito sono riportate le versioni minime supportate:

* Firefox versione minima 80
* Chrome versione minima 89
* Edge versione minima 90
* Safari versione minima 14




 a| 
Supporto per unità SSD FIPS 140-3 NVMe
 a| 
Sono ora supportati i dischi SSD NVMe FIPS 140-3 certificati NetApp. Verranno identificati correttamente come tali nel profilo dello storage array e in System Manager.



 a| 
Supporto della cache di lettura SSD su EF300 e EF600
 a| 
La cache di lettura SSD è ora supportata sui controller EF300 e EF600 che utilizzano HDD con un'espansione SAS.



 a| 
Supporto del mirroring remoto asincrono iSCSI e Fibre Channel su EF300 e EF600
 a| 
Il mirroring remoto asincrono (ARVM) è ora supportato sui controller EF300 e EF600 con volumi basati su NVMe e SAS.



 a| 
Supporto di EF300 e EF600 senza unità sul vassoio di base
 a| 
Sono ora supportate le configurazioni dei controller EF300 e EF600 senza unità NVMe sul vassoio di base.



 a| 
Porte USB disattivate per tutte le piattaforme
 a| 
Le porte USB sono ora disabilitate su tutte le piattaforme.



 a| 
Cache di lettura SSD aumentata massima
 a| 
Cache di lettura SSD massima aumentata da 5TB GB a 8TB TB.



 a| 
Assegna la cache in lettura all-flash a un singolo volume in configurazioni duplex
 a| 
È ora possibile assegnare tutta la cache in lettura SSD allo stesso volume sui sistemi duplex ogni volta che un singolo volume utilizza l'intera cache SSD.



 a| 
Numero di serie dell'unità aggiunto alla tabella riepilogativa del profilo dell'array di storage
 a| 
Il numero di serie dell'unità è stato aggiunto alla tabella di riepilogo dell'unità nel profilo Storage Array.



 a| 
Aggiunti dom0-misc-log all'ASUP giornaliero
 a| 
I registri dom0-misc per i controller A e B sono stati aggiunti agli ASP giornalieri.



 a| 
La porta 443 viene ora utilizzata per impostazione predefinita per la comunicazione tra applicazioni e servizi Web incorporati
 a| 
La porta 443 viene ora utilizzata per impostazione predefinita quando si comunica con il server Web incorporato. Il  `-useLegacyTransferPort` Il comando CLI è stato aggiunto per coloro che invece desiderano utilizzare la porta di trasferimento legacy 8443. Per ulteriori informazioni sul nuovo comando CLI -useLegacyTransferPort, vedere la https://docs.netapp.com/us-en/e-series-cli/whats-new.html["Novità di SANtricity CLI"].



 a| 
Capacità di avanzamento della parità del volume di scansione
 a| 
I seguenti comandi CLI sono stati implementati per supportare operazioni di scansione della parità di volume basate su processi:

* Avvia controllo parità volume
* Errori del processo di controllo parità del volume di salvataggio
* Interrompere il processo di verifica della parità del volume
* Mostra processi di controllo parità volume


Per ulteriori informazioni sui nuovi comandi CLI di scansione della parità del volume basati sui processi, consultare la https://docs.netapp.com/us-en/e-series-cli/whats-new.html["Novità di SANtricity CLI"].



 a| 
Supporto MFA per Unified Manager
 a| 
Il supporto dell'autenticazione a più fattori (MFA) è ora supportato in Unified Manager.



 a| 
Icona di attivazione/disattivazione per la vista hardware anteriore-posteriore
 a| 
Nella vista hardware di System Manager/Unified Manager, sono ora disponibili le due schede seguenti per controllare la vista anteriore e posteriore:

* Scheda Drives (unità)
* Scheda Controller e componenti




 a| 
Plug-in vCenter Storage
 a| 
Il plug-in vCenter Storage è stato aggiornato per verificarne la compatibilità con la release e-Series 11,80.



 a| 
Proxy dei servizi Web 6,0
 a| 
Web Services Proxy è stato aggiornato alla versione 6,0 per la compatibilità con la versione 11,80 di e-Series.



 a| 
Flag di creazione dei casi ASUP rimosso per gli eventi di superamento della temperatura nominale e massima di e-Series
 a| 
Il flag di creazione del caso è ora disabilitato per gli eventi di superamento della temperatura nominale e massima che non richiedono alcuna azione.



 a| 
Flag di creazione priorità caso attivato per l'evento 0x1209 Mel
 a| 
Viene ora creato un contrassegno di creazione del caso per `MEL_EV_DEGRADE_CHANNEL 0x1209` Evento MEL.

|===