---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: Nuove funzionalità di SANtricity OS. 
---
= Novità di SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La seguente tabella descrive le nuove funzionalità di SANtricity OS 11.8 per la gestione integrata dei controller EF300, EF600, E2800/EF280 e E5700/EF570.



== Nuove funzionalità della versione 11.80

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Enhanced Volume Parity Scan (scansione parity volume avanzata)
 a| 
La scansione della parità del volume può ora essere avviata come processo in background tramite l'API REST o tramite CLI. La scansione di parità risultante viene eseguita in background per tutto il tempo necessario per completare l'operazione di scansione. Le operazioni di scansione sopravvivono ai riavvii del controller e alle operazioni di failover.



 a| 
Supporto SAML per Unified Manager
 a| 
Unified Manager ora supporta SAML (Security Assertion Markup Language). Una volta abilitato SAML per Unified Manager, gli utenti devono utilizzare l'autenticazione a più fattori rispetto al provider di identità per interagire con l'interfaccia utente. Una volta abilitato SAML su Unified Manager, l'API REST non può essere utilizzata senza passare attraverso IdP per autenticare le richieste.



 a| 
Funzione di configurazione automatica
 a| 
Ora supporta la possibilità di impostare il parametro delle dimensioni del blocco del volume da utilizzare con la funzione di configurazione automatica per la configurazione iniziale dell'array. Questa funzione è disponibile nella CLI solo come parametro "blocksize".



 a| 
Firma crittografica del firmware del controller
 a| 
Il firmware del controller è firmato crittograficamente. Le firme vengono controllate durante il download iniziale e ad ogni avvio del controller. Nessun impatto previsto per l'utente finale. Le firme sono supportate da un certificato Extended Validation emesso dalla CA.



 a| 
Firma crittografica del firmware del disco
 a| 
Il firmware del disco è firmato crittograficamente. Le firme vengono controllate durante il download iniziale e supportate da un certificato Extended Validation emesso dalla CA. Il contenuto del firmware del disco viene ora fornito come file ZIP, che contiene il firmware precedente non firmato e il nuovo firmware firmato. L'utente deve scegliere il file appropriato in base alla versione di rilascio del codice in esecuzione sul sistema di destinazione.



 a| 
Gestione server chiavi esterne - dimensione chiave certificato
 a| 
La nuova chiave di certificato predefinita è di 3072 bit (da 2048). Sono supportate dimensioni delle chiavi fino a 4096 bit. Un bit NVSRAM deve essere modificato per supportare le dimensioni delle chiavi non predefinite.



 a| 
Supporto per pool di dischi dinamici di dimensioni maggiori utilizzando dischi con blocchi di dimensioni 512b
 a| 
I clienti che utilizzano il tipo di versione del pool versione 1 possono ora disporre di un pool di dischi di dimensioni massime pari a 48 TB. La versione precedente supporta pool di dischi fino a 24 TB. Se i pool di dischi esistenti devono essere convertiti in dimensioni maggiori, è necessario rimuovere prima tutti i volumi. Un'operazione di downgrade è limitata quando esiste un pool di dischi versione 1.



 a| 
System Manager e Unified Manager non verranno lanciati a meno che non vengano soddisfatti i requisiti minimi del browser
 a| 
È necessaria una versione minima del browser prima dell'avvio di System Manager o di Unified Manager. Di seguito sono riportate le versioni minime supportate:

* Firefox versione minima 80
* Chrome versione minima 89
* Edge versione minima 90
* Safari versione minima 14




 a| 
Supporto per unità SSD FIPS 140-3 NVMe
 a| 
Sono ora supportati i dischi SSD NVMe FIPS 140-3 certificati NetApp. Verranno identificati correttamente come tali nel profilo dello storage array e in System Manager.



 a| 
Supporto della cache di lettura SSD su EF300 e EF600
 a| 
La cache di lettura SSD è ora supportata sui controller EF300 e EF600 che utilizzano HDD con un'espansione SAS.



 a| 
Supporto del mirroring remoto asincrono iSCSI e Fibre Channel su EF300 e EF600
 a| 
Il mirroring remoto asincrono (ARVM) è ora supportato sui controller EF300 e EF600 con volumi basati su NVMe e SAS.



 a| 
Supporto di EF300 e EF600 senza unità sul vassoio di base
 a| 
Sono ora supportate le configurazioni dei controller EF300 e EF600 senza unità NVMe sul vassoio di base.



 a| 
Porte USB disattivate per tutte le piattaforme
 a| 
Le porte USB sono ora disabilitate su tutte le piattaforme.

|===