---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity, 12.0, 11.9, 11.8, EF80, EF50, E4000, EF300, EF600, E2800, EF280, E5700, EF570, 
summary: Nuove funzionalità di SANtricity OS. 
---
= Novità di SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La tabella seguente descrive le nuove funzionalità delle ultime release di SANtricity OS per la gestione integrata dei controller EF80, EF50, E4000, EF300, EF600, E2800/EF280 e E5700/EF570.



== Nuove funzionalità in Version 12.00


NOTE: La release SANtricity OS 12.00 è compatibile solo con i nuovi sistemi storage all-flash EF80 e EF50.

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Nuovi modelli di sistema storage – sistemi di storage all-flash EF80 e EF50
 a| 
Questa release introduce i sistemi di storage all-NVMe-flash EF80 e EF50. EF80 ed EF50 supportano 24 unità SSD NVMe e una scheda di mirroring inter-controller per ciascun controller. Le interfacce verso gli host NVMe over Fabrics supportate includono NVMe over RoCE, NVMe over IB, NVMe over FC per EF80 e NVMe over FC per EF50. L'interfaccia SCSI supportata è Fibre Channel per entrambi i sistemi. EF50 supporta fino a due schede di interfaccia verso gli host per controller, mentre EF80 supporta fino a tre schede di interfaccia verso gli host per controller.

Gli array EF80 ed EF50 supportano anche unità SSD NVMe ad alta capacità da 30TB o 60TB. Gli EF80 ed EF50 possono utilizzare la Dynamic Disk Pool solo quando l'array è popolato con unità da 30TB o 60TB.



 a| 
Nuova interfaccia utente per SANtricity System Manager
 a| 
Per i nuovi controller EF80 e EF50, l'interfaccia utente di SANtricity System Manager è stata riprogettata per offrire un aspetto e un'esperienza più moderni. La nuova interfaccia include una navigazione tramite pannello a sinistra e una maggiore facilità d'uso per semplificare le attività di gestione.



 a| 
I nomi alternativi del soggetto (SAN) per il certificato server ora consentono solo lettere, cifre e trattini
 a| 
Quando si crea o si modifica un certificato server in SANtricity System Manager o Unified Manager, il campo Subject Alternative Names (SANs) ora consente solo lettere, cifre e trattini. Questa modifica migliora la sicurezza e garantisce la compatibilità con gli standard di settore per i certificati SSL/TLS.



 a| 
La dimensione dei segmenti dei Dynamic Disk Pools ora è impostata di default a 32K per i sistemi basati su SSD e NVMe
 a| 
Per i Dynamic Disk Pools su sistemi basati su SSD e NVMe, la dimensione predefinita del segmento è stata modificata a 32K. In precedenza, la dimensione predefinita del segmento dei Dynamic Disk Pools era fissata a 128K per questi sistemi. Questa modifica ottimizza le prestazioni per i carichi di lavoro che coinvolgono un mix di operazioni di I/O di piccole e grandi dimensioni.



 a| 
L'editor di script è ora disponibile in SANtricity System Manager
 a| 
È ora disponibile un nuovo editor di script all'interno di SANtricity System Manager. L'editor di script consente di creare o modificare un file di script, salvare un file di script sul disco locale della stazione di gestione dello storage o caricare un file di script dal disco. L'editor di script offre funzionalità di controllo della sintassi ed esecuzione dei comandi per la gestione del sistema storage. Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/e-series-santricity/sm-support/use-script-editor.html["Utilizzo dell'editor di script"^].

|===


== Nuove funzionalità in Version 11.90R5

Questa versione contiene solo correzioni di errori e nessuna nuova funzionalità. Per ulteriori informazioni sulle modifiche in questa versione, consultare il README di E-Series SANtricity OS 11.90R5.



== Nuove funzionalità nella versione 11.90R4

Questa versione contiene solo piccole modifiche e nessuna nuova funzionalità. Per ulteriori informazioni sulle modifiche in questa versione, consultare il README di E-Series SANtricity OS 11.90R4.



== Nuove funzioni della versione 11.90R3

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Supporto del sistema operativo SANtricity per IOM12C e DCM3
 a| 
Il supporto per gli shelf SAS-3 IOM12C e DCM3 è ora disponibile per il firmware del controller 11.90R3 o superiore. Gli shelf IOM12C e DCM3 sostituiscono gli shelf IOM12B e DCM2.

|===


== Nuove funzioni della versione 11.90R2

Questa versione contiene solo modifiche minori e nessuna nuova funzionalità. Per ulteriori informazioni sulle modifiche apportate a questa versione, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP3334464["Note sulla versione di e-Series 11,90"^] .



== Nuove funzioni della versione 11.90R1

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Nuovi modelli di sistemi storage: EF300C e EF600C
 a| 
Questa release introduce i sistemi storage All Flash NVMe EF300C e EF600C. I sistemi EF300C e EF600C sono versioni flash a elevata capacità dei sistemi storage EF300 e EF600 esistenti. I dischi SSD NVMe a elevata capacità di 30TB o 60TB dimensioni sono supportati con EF300C e EF600C. EF300C/EF600C è compatibile solo per l'utilizzo con Dynamic Disk Pool, senza supporto RAID legacy.



 a| 
Supporto per interfacce SAS 12GB su controller E4000
 a| 
Il controller E4000 ora supporta 12GB schede di interfaccia host SAS.

|===


== Nuove funzionalità della versione 11.90

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Nuovo modello di sistema storage – E4000
 a| 
Questa release introduce il sistema di storage a basso costo E4000. E4000 supporta unità da 12 e 60 GB e una singola scheda di interfaccia host (HIC) per controller. Per la versione iniziale, le schede di interfaccia host supportate includono iSCSI e Fibre Channel. In Unified Manager è possibile visualizzare e gestire i sistemi storage E4000 e altri sistemi storage e-Series.



 a| 
Maggiore capacità per Dynamic Disk Pools
 a| 
La capacità dei Dynamic Disk Pools (DDP) è stata aumentata a 12 PB ogniqualvolta la capacità di ciascuno dei singoli dischi del pool è superiore a 23 TB. Se la capacità dei singoli dischi è inferiore a 23 TB, la capacità DDP è 6 PB.



 a| 
Impostazioni di scansione dei supporti predefinite aumentate
 a| 
La velocità di scansione predefinita dei supporti è stata aumentata a 120 giorni.



 a| 
Chiave privata ora accettata per la gestione esterna delle chiavi
 a| 
Il file CSR (Certificate Signing Request) generato esternamente tramite coppie di chiavi private e pubbliche può ora essere importato tramite System Manager.



 a| 
La funzione di blocco dell'accesso è ora disponibile per i servizi Web
 a| 
Configurabile solo tramite l'API REST, è ora disponibile una nuova impostazione di blocco dell'accesso per i servizi Web incorporati e proxy.

|===


== Nuove funzioni della versione 11.80.1R4

Questa versione contiene solo modifiche minori e nessuna nuova funzionalità o restrizioni. Per ulteriori informazioni sulle modifiche apportate a questa versione, fare riferimento al file README.



== Nuove funzioni della versione 11.80.1R3

Questa versione contiene solo modifiche minori e nessuna nuova funzionalità o restrizioni. Per ulteriori informazioni sulle modifiche apportate a questa versione, fare riferimento al file README.



== Nuove funzioni della versione 11.80.1R2

Questa versione contiene solo modifiche minori e nessuna nuova funzionalità o restrizioni. Per ulteriori informazioni sulle modifiche apportate a questa versione, fare riferimento al file README.



== Nuove funzioni della versione 11.80.1R1

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Maggiore lunghezza della chiave per i nuovi certificati di gestione autofirmati e con firma CA.
 a| 
La lunghezza della chiave del certificato di gestione per il certificato autofirmato delle applicazioni SANtricity System Manager e Unified Manager è stata modificata da 2048 a 3072 bit. La modifica si applica ai certificati autofirmati e con firma CA generati di recente dalle applicazioni SANtricity. La lunghezza della chiave è fissa e non è influenzata dalle definizioni delle dimensioni della chiave predefinite in NVSRAM.

|===


== Nuove funzioni della versione 11.80.1

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
`-identifyDevices` parametro
 a| 
A new `-identifyDevices` parametro è ora disponibile in SMcli. Questo nuovo parametro consente di cercare tutti i dispositivi a blocchi nativi SCSI associati ai tuoi Storage Arrays. Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-Devices["Parametri della riga di comando SMcli scaricabili"^].



 a| 
Statistiche del kernel Ethernet
 a| 
Una nuova opzione Ethernet Kernel Statistics è ora disponibile nella pagina Visualizza pacchetti di statistiche iSCSI in System Manager. Questa nuova opzione consente di visualizzare le statistiche per i driver del kernel della piattaforma del dispositivo iSCSI. Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/e-series-santricity/sm-support/view-iscsi-statistics-packages-support.html["Visualizza i pacchetti di statistiche iSCSI"^].



 a| 
Aggiunta la capacità di bloccare gli indirizzi IP tramite l'endpoint REST API
 a| 
Gli utenti possono ora bloccare indirizzi IP specifici tramite l'endpoint Impostazioni (`/devmgr/v2/settings`). Una volta configurato tramite l'endpoint Impostazioni, solo gli indirizzi IP specificati tramite una whitelist possono comunicare con il dispositivo di archiviazione. Questa nuova funzione supporta gli elenchi di indirizzi IPv4 e IPv6.



 a| 
Plug-in vCenter Storage
 a| 
Il plug-in vCenter Storage è stato aggiornato per verificarne la compatibilità con la release e-Series 11.80.1.



 a| 
Proxy dei servizi Web
 a| 
Web Services Proxy è stato aggiornato alla versione 6,1 per la compatibilità con la versione 11.80.1 di e-Series.

|===


== Nuove funzionalità della versione 11.80

[cols="35h,~"]
|===
| Nuova funzionalità | Descrizione 


 a| 
Enhanced Volume Parity Scan (scansione parity volume avanzata)
 a| 
La scansione della parità del volume può ora essere avviata come processo in background tramite l'API REST o tramite CLI. La scansione di parità risultante viene eseguita in background per tutto il tempo necessario per completare l'operazione di scansione. Le operazioni di scansione sopravvivono ai riavvii del controller e alle operazioni di failover.



 a| 
Supporto SAML per Unified Manager
 a| 
Unified Manager ora supporta SAML (Security Assertion Markup Language). Una volta abilitato SAML per Unified Manager, gli utenti devono utilizzare l'autenticazione a più fattori rispetto al provider di identità per interagire con l'interfaccia utente. Una volta abilitato SAML su Unified Manager, l'API REST non può essere utilizzata senza passare attraverso IdP per autenticare le richieste.



 a| 
Funzione di configurazione automatica
 a| 
Ora supporta la possibilità di impostare il parametro delle dimensioni del blocco del volume da utilizzare con la funzione di configurazione automatica per la configurazione iniziale dell'array. Questa funzione è disponibile nella CLI solo come parametro "blocksize".



 a| 
Firma crittografica del firmware del controller
 a| 
Il firmware del controller è firmato crittograficamente. Le firme vengono controllate durante il download iniziale e ad ogni avvio del controller. Nessun impatto previsto per l'utente finale. Le firme sono supportate da un certificato Extended Validation emesso dalla CA.



 a| 
Firma crittografica del firmware del disco
 a| 
Il firmware del disco è firmato crittograficamente. Le firme vengono controllate durante il download iniziale e supportate da un certificato Extended Validation emesso dalla CA. Il contenuto del firmware del disco viene ora fornito come file ZIP, che contiene il firmware precedente non firmato e il nuovo firmware firmato. L'utente deve scegliere il file appropriato in base alla versione di rilascio del codice in esecuzione sul sistema di destinazione.



 a| 
Gestione server chiavi esterne - dimensione chiave certificato
 a| 
La nuova chiave di certificato predefinita è di 3072 bit (da 2048). Sono supportate dimensioni delle chiavi fino a 4096 bit. Un bit NVSRAM deve essere modificato per supportare le dimensioni delle chiavi non predefinite.

I valori di selezione delle dimensioni chiave sono i seguenti:

* VALORE PREDEFINITO = 0
* LUNGHEZZA 2048 = 1
* LUNGHEZZA 3072 = 2
* LUNGHEZZA 4096 = 3


Per modificare la dimensione della chiave in 4096 tramite SMcli:

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

Interrogare le dimensioni della chiave:

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
Miglioramenti dei pool di dischi
 a| 
I pool di dischi creati con i controller che eseguono la versione 11,80 o superiore saranno _pool versione 1_ anziché _pool versione 0_. Un'operazione di downgrade è limitata quando esiste un pool di dischi _versione 1_.

La versione di un pool di dischi può essere identificata nel profilo dell'array di storage.



 a| 
System Manager e Unified Manager non verranno lanciati a meno che non vengano soddisfatti i requisiti minimi del browser
 a| 
È necessaria una versione minima del browser prima dell'avvio di System Manager o di Unified Manager.

Di seguito sono riportate le versioni minime supportate:

* Firefox versione minima 80
* Chrome versione minima 89
* Edge versione minima 90
* Safari versione minima 14




 a| 
Supporto per unità SSD FIPS 140-3 NVMe
 a| 
Sono ora supportati i dischi SSD NVMe FIPS 140-3 certificati NetApp. Verranno identificati correttamente come tali nel profilo dello storage array e in System Manager.



 a| 
Supporto della cache di lettura SSD su EF300 e EF600
 a| 
La cache di lettura SSD è ora supportata sui controller EF300 e EF600 che utilizzano HDD con un'espansione SAS.



 a| 
Supporto del mirroring remoto asincrono iSCSI e Fibre Channel su EF300 e EF600
 a| 
Il mirroring remoto asincrono (ARVM) è ora supportato sui controller EF300 e EF600 con volumi basati su NVMe e SAS.



 a| 
Supporto di EF300 e EF600 senza unità sul vassoio di base
 a| 
Sono ora supportate le configurazioni dei controller EF300 e EF600 senza unità NVMe sul vassoio di base.



 a| 
Porte USB disattivate per tutte le piattaforme
 a| 
Le porte USB sono ora disabilitate su tutte le piattaforme.



 a| 
Cache di lettura SSD aumentata massima
 a| 
Cache di lettura SSD massima aumentata da 5TB GB a 8TB TB.



 a| 
Assegna la cache in lettura all-flash a un singolo volume in configurazioni duplex
 a| 
È ora possibile assegnare tutta la cache in lettura SSD allo stesso volume sui sistemi duplex ogni volta che un singolo volume utilizza l'intera cache SSD.



 a| 
Numero di serie dell'unità aggiunto alla tabella riepilogativa del profilo dell'array di storage
 a| 
Il numero di serie dell'unità è stato aggiunto alla tabella di riepilogo dell'unità nel profilo Storage Array.



 a| 
Aggiunti dom0-misc-log all'ASUP giornaliero
 a| 
I registri dom0-misc per i controller A e B sono stati aggiunti agli ASP giornalieri.



 a| 
La porta 443 viene ora utilizzata per impostazione predefinita per la comunicazione tra applicazioni e servizi Web incorporati
 a| 
La porta 443 viene ora utilizzata per impostazione predefinita quando si comunica con il server Web incorporato. Il  `-useLegacyTransferPort` Il comando CLI è stato aggiunto per coloro che invece desiderano utilizzare la porta di trasferimento legacy 8443. Per ulteriori informazioni sul nuovo comando CLI -useLegacyTransferPort, vedere la https://docs.netapp.com/us-en/e-series-cli/whats-new.html["Novità di SANtricity CLI"].



 a| 
Capacità di avanzamento della parità del volume di scansione
 a| 
I seguenti comandi CLI sono stati implementati per supportare operazioni di scansione della parità di volume basate su processi:

* Avvia controllo parità volume
* Errori del processo di controllo parità del volume di salvataggio
* Interrompere il processo di verifica della parità del volume
* Mostra processi di controllo parità volume


Per ulteriori informazioni sui nuovi comandi CLI di scansione della parità del volume basati sui processi, consultare la https://docs.netapp.com/us-en/e-series-cli/whats-new.html["Novità di SANtricity CLI"].



 a| 
Supporto MFA per Unified Manager
 a| 
Il supporto dell'autenticazione a più fattori (MFA) è ora supportato in Unified Manager.



 a| 
Icona di attivazione/disattivazione per la vista hardware anteriore-posteriore
 a| 
Nella vista hardware di System Manager/Unified Manager, sono ora disponibili le due schede seguenti per controllare la vista anteriore e posteriore:

* Scheda Drives (unità)
* Scheda Controller e componenti




 a| 
Plug-in vCenter Storage
 a| 
Il plug-in vCenter Storage è stato aggiornato per verificarne la compatibilità con la release e-Series 11,80.



 a| 
Proxy dei servizi Web 6,0
 a| 
Web Services Proxy è stato aggiornato alla versione 6,0 per la compatibilità con la versione 11,80 di e-Series.



 a| 
Flag di creazione dei casi ASUP rimosso per gli eventi di superamento della temperatura nominale e massima di e-Series
 a| 
Il flag di creazione del caso è ora disabilitato per gli eventi di superamento della temperatura nominale e massima che non richiedono alcuna azione.



 a| 
Flag di creazione priorità caso attivato per l'evento 0x1209 Mel
 a| 
Viene ora creato un contrassegno di creazione del caso per `MEL_EV_DEGRADE_CHANNEL 0x1209` Evento MEL.

|===