---
permalink: config-vmware/configure-multipath-software-concept.html 
sidebar: sidebar 
keywords: multipath software for vmware, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Configurare il software m in modo da fornire un percorso ridondante all"array di storage in caso di interruzione di uno dei percorsi fisici.' 
---
= Configurare il software multipath
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per fornire un percorso ridondante all'array di storage, è possibile configurare il software multipath.

Il software multipath fornisce un percorso ridondante all'array di storage in caso di interruzione di uno dei percorsi fisici. Il software multipath presenta il sistema operativo con un singolo dispositivo virtuale che rappresenta i percorsi fisici attivi verso lo storage. Il software multipath gestisce anche il processo di failover che aggiorna il dispositivo virtuale. Per VMware, NVMe/FC utilizza il plug-in ad alte prestazioni (HPP).

Applicabile solo per i protocolli FC, iSCSI e SAS, VMware fornisce plug-in, noti come Storage Array Type Plug-in (SATP), per gestire le implementazioni di failover di array di storage` di vendor specifici.

L'SATP da utilizzare è *VMW_SATP_ALUA*.

Per ulteriori informazioni, vedere https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-DB5BC795-E4D9-4350-9C5D-12BB3C0E6D99.html["VMware SATP"^].
