---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-storage-array-discovery.html 
keywords: discover arrays vCenter plugin, discover storage resources Plugin for vCenter, resolve certificates vCenter plugin 
summary: 'Utilizzare l"interfaccia Plugin per vCenter per rilevare gli indirizzi IP degli array nella rete.' 
---
= Scopri gli storage array nel plug-in di storage SANtricity per vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per visualizzare e gestire le risorse di storage, è necessario utilizzare l'interfaccia Storage Plugin for vCenter per rilevare gli indirizzi IP degli array nella rete.

.Prima di iniziare
* È necessario conoscere gli indirizzi IP di rete (o l'intervallo di indirizzi) degli array controller.
* Gli array di storage devono essere configurati e configurati correttamente, nonché conoscere le credenziali di accesso (nome utente e password).




== Fase 1: Inserire gli indirizzi di rete per il rilevamento

.Fasi
. Dalla pagina Gestisci, selezionare *Aggiungi/rileva*.
+
Viene visualizzata la finestra di dialogo Immetti intervallo indirizzi di rete.

. Effettuare una delle seguenti operazioni:
+
** Per rilevare un array, selezionare il pulsante di opzione *Discover a single storage array* (rileva un singolo array di storage), quindi immettere l'indirizzo IP di uno dei controller dell'array di storage.
** Per rilevare più array di storage, selezionare il pulsante di opzione *Discover all storage array in a network range* (rileva tutti gli array di storage all'interno di un intervallo di rete), quindi immettere l'indirizzo di rete iniziale e l'indirizzo di rete finale per eseguire la ricerca nella sottorete locale.


. Fare clic su *Avvia rilevamento*.
+
All'inizio del processo di rilevamento, la finestra di dialogo visualizza gli array di storage rilevati. Il completamento del processo di rilevamento potrebbe richiedere alcuni minuti.

+
Se non vengono rilevati array gestibili, verificare che gli array di storage siano collegati correttamente alla rete e che gli indirizzi assegnati rientrino nell'intervallo. Fare clic su *New Discovery Parameters* (nuovi parametri di rilevamento) per tornare alla pagina Add/Discover (Aggiungi/rileva).

. Selezionare la casella di controllo accanto a qualsiasi array di storage che si desidera aggiungere al dominio di gestione.
+
Il sistema esegue un controllo delle credenziali su ogni array che si sta aggiungendo al dominio di gestione. Prima di procedere, potrebbe essere necessario risolvere eventuali problemi relativi ai certificati non attendibili.

. Fare clic su *Avanti* per passare alla fase successiva della procedura guidata.
+
Se gli array di storage dispongono di certificati validi, passare a. <<Fase 3: Fornire le password>>.

+
Se gli array di storage non dispongono di certificati validi, viene visualizzata la finestra di dialogo Risolvi certificati autofirmati. Passare a. <<Fase 2: Risoluzione dei certificati non attendibili durante il rilevamento>>.

+
Se si desidera importare i certificati firmati dalla CA, annullare la procedura guidata di rilevamento e fare clic su *Certificate Management* (Gestione certificati) nel pannello a sinistra. Per ulteriori informazioni, consultare la guida in linea.





== Fase 2: Risoluzione dei certificati non attendibili durante il rilevamento

È necessario risolvere eventuali problemi di certificato prima di procedere con il processo di rilevamento.

. Se viene visualizzata la finestra di dialogo Risolvi certificati autofirmati, esaminare le informazioni visualizzate per i certificati non attendibili. Per ulteriori informazioni, fare clic sui puntini di sospensione all'estremità della tabella e selezionare *View* (Visualizza) dal menu a comparsa.
. Effettuare una delle seguenti operazioni:
+
** Se le connessioni agli array di storage rilevati sono attendibili, fare clic su *Avanti*, quindi su *Sì* per confermare e passare alla finestra di dialogo successiva della procedura guidata. I certificati autofirmati sono contrassegnati come attendibili e gli array di storage vengono aggiunti al plug-in.
** Se le connessioni agli array di storage non sono attendibili, selezionare *Annulla* e convalidare la strategia di certificato di sicurezza di ciascun array di storage prima di aggiungerne una.


. Fare clic su *Avanti* per passare alla fase successiva della procedura guidata.




== Fase 3: Fornire le password

Come ultimo passaggio per il rilevamento, è necessario immettere le password per gli array di storage che si desidera aggiungere al dominio di gestione.

. Per ogni array rilevato, inserire la password admin nei campi.
. Fare clic su *fine*.
+
Il sistema può impiegare diversi minuti per connettersi agli array di storage specificati. Al termine del processo, gli array di storage vengono aggiunti al dominio di gestione e associati al gruppo selezionato (se specificato).


