---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-raid-level-is-best-for-my-application.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Per massimizzare le performance di un gruppo di volumi, è necessario selezionare il livello RAID appropriato. 
---
= Qual è il livello RAID migliore per la mia applicazione?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per massimizzare le performance di un gruppo di volumi, è necessario selezionare il livello RAID appropriato.

È possibile determinare il livello RAID appropriato conoscendo le percentuali di lettura e scrittura per le applicazioni che accedono al gruppo di volumi. Utilizzare la pagina Performance (prestazioni) per ottenere queste percentuali.



== Livelli RAID e performance applicative

RAID si basa su una serie di configurazioni, chiamate livelli, per determinare il modo in cui i dati di ridondanza e utente vengono scritti e recuperati dai dischi. Ogni livello RAID offre diverse funzionalità di performance. Le applicazioni con un'elevata percentuale di lettura sono in grado di funzionare correttamente utilizzando volumi RAID 5 o RAID 6, a causa delle eccezionali prestazioni di lettura delle configurazioni RAID 5 e RAID 6.

Le applicazioni con una bassa percentuale di lettura (elevata intensità di scrittura) non funzionano altrettanto sui volumi RAID 5 o RAID 6. Le prestazioni degradate sono il risultato del modo in cui un controller scrive i dati e i dati di ridondanza sui dischi di un gruppo di volumi RAID 5 o RAID 6.

Selezionare un livello RAID in base alle seguenti informazioni.



=== RAID 0

*Descrizione:*

* Non ridondante, modalità striping.
* RAID 0 esegue lo striping dei dati su tutti i dischi del gruppo di volumi.


*Caratteristiche di protezione dei dati:*

* RAID 0 non è consigliato per esigenze di alta disponibilità. RAID 0 è migliore per i dati non critici.
* Se un singolo disco si guasta nel gruppo di volumi, tutti i volumi associati si guastano e tutti i dati vengono persi.


*Requisiti del numero di unità:*

* Per RAID livello 0 è richiesto un minimo di un disco.
* I gruppi di volumi RAID 0 possono avere più di 30 dischi.
* È possibile creare un gruppo di volumi che includa tutte le unità dell'array di storage.




=== RAID 1 o RAID 10

*Descrizione:*

* Modalità striping/mirror.


*Come funziona:*

* RAID 1 utilizza il mirroring del disco per scrivere i dati su due dischi duplicati contemporaneamente.
* RAID 10 utilizza lo striping dei dischi per eseguire lo striping dei dati su un set di coppie di dischi mirrorati.


*Caratteristiche di protezione dei dati:*

* RAID 1 e RAID 10 offrono performance elevate e la migliore disponibilità dei dati.
* RAID 1 e RAID 10 utilizzano il mirroring del disco per eseguire una copia esatta da un disco a un altro.
* Se uno dei dischi di una coppia di dischi si guasta, lo storage array può passare istantaneamente all'altro disco senza alcuna perdita di dati o di servizio.
* Un guasto a un singolo disco causa il degrado dei volumi associati. L'unità mirror consente di accedere ai dati.
* Un errore di coppia di dischi in un gruppo di volumi causa il malfunzionamento di tutti i volumi associati e la perdita di dati.


*Requisiti del numero di unità:*

* Per RAID 1 sono necessari almeno due dischi: Un disco per i dati dell'utente e un disco per i dati mirrorati.
* Se si selezionano quattro o più dischi, RAID 10 viene configurato automaticamente nel gruppo di volumi: Due dischi per i dati dell'utente e due dischi per i dati mirrorati.
* È necessario disporre di un numero pari di dischi nel gruppo di volumi. Se non si dispone di un numero pari di dischi e si dispone di altri dischi non assegnati, passare a *Pools & Volume Groups* per aggiungere ulteriori dischi al gruppo di volumi e riprovare l'operazione.
* I gruppi di volumi RAID 1 e RAID 10 possono avere più di 30 dischi. È possibile creare un gruppo di volumi che includa tutte le unità dell'array di storage.




=== RAID 5

*Descrizione:*

* Modalità i/o elevata.


*Come funziona:*

* I dati dell'utente e le informazioni ridondanti (parità) vengono sottoposti a striping tra i dischi.
* La capacità equivalente di un disco viene utilizzata per le informazioni ridondanti.


*Caratteristiche di protezione dei dati*

* Se un singolo disco si guasta in un gruppo di volumi RAID 5, tutti i volumi associati diventano degradati. Le informazioni ridondanti consentono di accedere ai dati.
* Se due o più dischi si guastano in un gruppo di volumi RAID 5, tutti i volumi associati si guastano e tutti i dati vengono persi.


*Requisiti del numero di unità:*

* È necessario disporre di un minimo di tre dischi nel gruppo di volumi.
* In genere, il gruppo di volumi è limitato a un massimo di 30 dischi.




=== RAID 6

*Descrizione:*

* Modalità i/o elevata.


*Come funziona:*

* I dati dell'utente e le informazioni ridondanti (doppia parità) vengono sottoposti a striping tra i dischi.
* La capacità equivalente di due dischi viene utilizzata per le informazioni ridondanti.


*Caratteristiche di protezione dei dati:*

* Se uno o due dischi si guastano in un gruppo di volumi RAID 6, tutti i volumi associati diventano degradati, ma le informazioni ridondanti consentono di continuare ad accedere ai dati.
* Se tre o più dischi si guastano in un gruppo di volumi RAID 6, tutti i volumi associati si guastano e tutti i dati vengono persi.


*Requisiti del numero di unità:*

* È necessario disporre di un minimo di cinque dischi nel gruppo di volumi.
* In genere, il gruppo di volumi è limitato a un massimo di 30 dischi.



NOTE: Non è possibile modificare il livello RAID di un pool. L'interfaccia utente configura automaticamente i pool come RAID 6.



== Livelli RAID e protezione dei dati

RAID 1, RAID 5 e RAID 6 scrivono i dati di ridondanza sul disco per la tolleranza di errore. I dati di ridondanza possono essere una copia dei dati (mirrorati) o un codice di correzione degli errori derivato dai dati. È possibile utilizzare i dati di ridondanza per ricostruire rapidamente le informazioni su un disco sostitutivo in caso di guasto.

È possibile configurare un singolo livello RAID in un singolo gruppo di volumi. Tutti i dati di ridondanza per quel gruppo di volumi vengono memorizzati all'interno del gruppo di volumi. La capacità del gruppo di volumi è la capacità aggregata dei dischi membri meno la capacità riservata ai dati di ridondanza. La quantità di capacità necessaria per la ridondanza dipende dal livello RAID utilizzato.
