---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-turn-on-locator-lights.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: È possibile individuare le unità per identificare fisicamente tutte le unità che comprendono un pool, un gruppo di volumi o una cache SSD selezionata. Un indicatore LED si accende su ogni disco nel pool, gruppo di volumi o cache SSD selezionato. 
---
= Accendere le luci di individuazione
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile individuare le unità per identificare fisicamente tutte le unità che comprendono un pool, un gruppo di volumi o una cache SSD selezionata. Un indicatore LED si accende su ogni disco nel pool, gruppo di volumi o cache SSD selezionato.

.Fasi
. Dalla pagina Manage (Gestione), selezionare l'array di storage.
. Selezionare menu:Provisioning[Configure Pools and Volume Groups] (Configura pool e gruppi di volumi).
. Selezionare il pool, il gruppo di volumi o la cache SSD che si desidera individuare, quindi fare clic su menu:More[Turn on locator lights] (attiva indicatori di ricerca).
+
Viene visualizzata una finestra di dialogo che indica che le spie dei dischi che compongono il pool, il gruppo di volumi o la cache SSD selezionati sono accese.

. Una volta individuati correttamente i dischi, fare clic su *Spegni*.

