---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-certificates-for-arrays.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Importare i certificati per gli array di storage in modo che possano autenticarsi con il sistema che ospita lo Storage Plugin per vCenter. 
---
= Importare certificati per gli array
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se necessario, è possibile importare i certificati per gli array di storage in modo che possano autenticarsi con il sistema che ospita lo Storage Plugin per vCenter. I certificati possono essere firmati da un'autorità di certificazione (CA) o autofirmati.

.Prima di iniziare
Se si importano certificati attendibili, è necessario importarli per i controller degli array di storage utilizzando System Manager.

.Fasi
. Selezionare *Certificate Management* (Gestione certificati).
. Selezionare la scheda *Trusted*.
+
Questa pagina mostra tutti i certificati segnalati per gli array di storage.

. Selezionare il menu:Importa[certificati] per importare un certificato CA oppure il menu:Importa[certificati array storage autofirmati] per importare un certificato autofirmato.
. Per limitare la visualizzazione, è possibile utilizzare il campo di filtraggio *Mostra certificati...* oppure ordinare le righe dei certificati facendo clic su una delle intestazioni di colonna.
. Nella finestra di dialogo, selezionare il certificato e fare clic su *Importa*.
+
Il certificato viene caricato e validato.


