---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-provisioning-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'È possibile creare container di dati, chiamati volumi, in modo che l"host possa accedere allo storage sull"array.' 
---
= Panoramica sul provisioning
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nel plug-in Storage per vCenter, è possibile creare container di dati, chiamati volumi, in modo che l'host possa accedere allo storage sull'array.



== Tipi di volume e caratteristiche

I volumi sono container di dati che gestiscono e organizzano lo spazio di storage sull'array di storage.

È possibile creare volumi dalla capacità di storage disponibile sull'array di storage, che consente di organizzare le risorse del sistema. Il concetto di "volumi" è simile all'utilizzo di cartelle/directory su un computer per organizzare i file per un accesso rapido.

I volumi sono l'unico livello di dati visibile agli host. In un ambiente SAN, i volumi vengono mappati ai LUN (Logical Unit Number). Queste LUN conservano i dati utente accessibili mediante uno o più protocolli di accesso host supportati dallo storage array, tra cui FC, iSCSI e SAS.

Ciascun volume di un pool o di un gruppo di volumi può avere le proprie caratteristiche individuali in base al tipo di dati che verranno memorizzati in esso. Alcune di queste caratteristiche includono:

* *Dimensione segmento* -- Un segmento è la quantità di dati in kilobyte (KiB) che viene memorizzata su un disco prima che lo storage array passi al disco successivo nello stripe (gruppo RAID). La dimensione del segmento è uguale o inferiore alla capacità del gruppo di volumi. La dimensione del segmento è fissa e non può essere modificata per i pool.
* *Capacità* -- consente di creare un volume dalla capacità libera disponibile in un pool o in un gruppo di volumi. Prima di creare un volume, il pool o il gruppo di volumi deve già esistere e disporre di capacità libera sufficiente per creare il volume.
* *Controller ownership* -- tutti gli storage array possono avere uno o due controller. Su un array a controller singolo, il carico di lavoro di un volume viene gestito da un singolo controller. Su un array a controller doppio, un volume avrà un controller preferito (A o B) che "possiede" il volume. In una configurazione a controller doppio, la proprietà del volume viene regolata automaticamente utilizzando la funzione di bilanciamento automatico del carico per correggere eventuali problemi di bilanciamento del carico quando i carichi di lavoro si spostano tra i controller. Il bilanciamento automatico del carico fornisce il bilanciamento automatizzato del carico di lavoro i/o e garantisce che il traffico i/o in entrata dagli host sia gestito dinamicamente e bilanciato tra entrambi i controller.
* *Assegnazione del volume* -- è possibile consentire agli host di accedere a un volume sia quando si crea il volume che in un secondo momento. Tutti gli accessi host vengono gestiti tramite un numero di unità logica (LUN). Gli host rilevano le LUN che, a loro volta, sono assegnate ai volumi. Se si assegna un volume a più host, utilizzare il software di clustering per assicurarsi che il volume sia disponibile per tutti gli host.
+
Il tipo di host può avere limiti specifici sul numero di volumi a cui l'host può accedere. Tenere presente questa limitazione quando si creano volumi per l'utilizzo da parte di un determinato host.

* *Resource provisioning* -- per gli array storage EF600 o EF300, è possibile specificare che i volumi vengano utilizzati immediatamente senza alcun processo di inizializzazione in background. Un volume con provisioning di risorse è un volume denso in un gruppo di volumi o pool SSD, in cui la capacità del disco viene allocata (assegnata al volume) quando viene creato il volume, ma i blocchi disco vengono disallocati (non mappati).
* *Descrivi name* -- puoi assegnare un nome a un volume qualsiasi, ma ti consigliamo di renderlo descrittivo.


Durante la creazione del volume, a ciascun volume viene allocata la capacità e viene assegnato un nome, una dimensione del segmento (solo gruppi di volumi), una proprietà del controller e un'assegnazione volume-a-host. I dati dei volumi vengono automaticamente bilanciati in base alle esigenze dei controller.



== Capacità per i volumi

I dischi dell'array di storage forniscono la capacità fisica dello storage per i dati. Prima di iniziare a memorizzare i dati, è necessario configurare la capacità allocata in componenti logici noti come pool o gruppi di volumi. Questi oggetti storage vengono utilizzati per configurare, memorizzare, gestire e conservare i dati sull'array di storage.



=== Capacità di creare ed espandere volumi

È possibile creare volumi dalla capacità non assegnata o dalla capacità libera in un pool o un gruppo di volumi.

* Quando si crea un volume dalla capacità non assegnata, è possibile creare contemporaneamente un pool o un gruppo di volumi e il volume.
* Quando si crea un volume dalla capacità libera, si crea un volume aggiuntivo su un pool o un gruppo di volumi già esistente.dopo aver espanso la capacità del volume, è necessario aumentare manualmente le dimensioni del file system per ottenere una corrispondenza. Il modo in cui si esegue questa operazione dipende dal file system in uso. Per ulteriori informazioni, consultare la documentazione del sistema operativo host.



NOTE: L'interfaccia del plug-in non fornisce un'opzione per creare volumi thin.



=== Capacità dei volumi riportata

La capacità del volume riportata è uguale alla quantità di capacità dello storage fisico allocata. Deve essere presente l'intera quantità di capacità dello storage fisico. Lo spazio fisicamente allocato è uguale allo spazio riportato all'host.

Di norma, si imposta la capacità del volume indicata come capacità massima a cui si pensa che il volume crescerà. I volumi offrono performance elevate e prevedibili per le applicazioni, soprattutto perché tutta la capacità dell'utente viene riservata e allocata al momento della creazione.



=== Limiti di capacità

La capacità minima di un volume è di 1 MiB e la capacità massima è determinata dal numero e dalla capacità dei dischi nel pool o nel gruppo di volumi.

Quando si aumenta la capacità di un volume segnalata, tenere presenti le seguenti linee guida:

* È possibile specificare fino a tre cifre decimali (ad esempio, 65.375 GiB).
* La capacità deve essere inferiore o uguale al massimo disponibile nel gruppo di volumi. Quando si crea un volume, viene preallocata una certa capacità aggiuntiva per la migrazione DSS (Dynamic Segment Size). La migrazione DSS è una funzione del software che consente di modificare le dimensioni dei segmenti di un volume.
* Alcuni sistemi operativi host supportano volumi superiori a 2 TIB (la capacità massima indicata è determinata dal sistema operativo host). Infatti, alcuni sistemi operativi host supportano fino a 128 volumi TIB. Per ulteriori informazioni, consultare la documentazione del sistema operativo host.




== Carichi di lavoro specifici dell'applicazione

Quando si crea un volume, si seleziona un carico di lavoro per personalizzare la configurazione dell'array di storage per un'applicazione specifica.

Un workload è un oggetto storage che supporta un'applicazione. È possibile definire uno o più carichi di lavoro o istanze per applicazione. Per alcune applicazioni, il sistema configura il carico di lavoro in modo che contenga volumi con caratteristiche di volume sottostanti simili. Queste caratteristiche dei volumi sono ottimizzate in base al tipo di applicazione supportata dal carico di lavoro. Ad esempio, se si crea un carico di lavoro che supporta un'applicazione Microsoft SQL Server e successivamente si creano volumi per tale carico di lavoro, le caratteristiche del volume sottostante sono ottimizzate per supportare Microsoft SQL Server.

Durante la creazione del volume, il sistema richiede di rispondere alle domande sull'utilizzo di un carico di lavoro. Ad esempio, se si creano volumi per Microsoft Exchange, viene chiesto quante cassette postali sono necessarie, quali sono i requisiti medi di capacità delle caselle postali e quante copie del database si desidera. Il sistema utilizza queste informazioni per creare una configurazione ottimale del volume, che può essere modificata in base alle esigenze. In alternativa, è possibile saltare questo passaggio nella sequenza di creazione del volume.



=== Tipi di carichi di lavoro

È possibile creare due tipi di carichi di lavoro: Specifici dell'applicazione e altri.

* *Specifico dell'applicazione* -- quando si creano volumi utilizzando un carico di lavoro specifico dell'applicazione, il sistema consiglia una configurazione del volume ottimizzata per ridurre al minimo i conflitti tra i/o del carico di lavoro dell'applicazione e altro traffico dall'istanza dell'applicazione. Le caratteristiche del volume come il tipo di i/o, le dimensioni del segmento, la proprietà del controller e la cache di lettura e scrittura sono automaticamente consigliate e ottimizzate per i carichi di lavoro creati per i seguenti tipi di applicazioni.
+
** Microsoft SQL Server
** Server Microsoft Exchange
** Applicazioni di videosorveglianza
** VMware ESXi (per volumi da utilizzare con Virtual Machine file System)
+
È possibile rivedere la configurazione del volume consigliata e modificare, aggiungere o eliminare i volumi e le caratteristiche consigliate dal sistema utilizzando la finestra di dialogo Add/Edit Volumes (Aggiungi/Modifica volumi).



* *Altri (o applicazioni senza supporto specifico per la creazione di volumi)* -- Altri carichi di lavoro utilizzano una configurazione del volume che è necessario specificare manualmente quando si desidera creare un carico di lavoro non associato a un'applicazione specifica o se il sistema non dispone di ottimizzazione integrata per l'applicazione che si intende utilizzare sull'array di storage. Specificare manualmente la configurazione del volume utilizzando la finestra di dialogo Add/Edit Volumes (Aggiungi/Modifica volumi).




=== Viste delle applicazioni e dei workload

Per visualizzare applicazioni e carichi di lavoro, avviare System Manager. Da questa interfaccia è possibile visualizzare le informazioni associate a un carico di lavoro specifico dell'applicazione in due modi diversi:

* È possibile selezionare la scheda Applications & workload (applicazioni e carichi di lavoro) nel riquadro Volumes (volumi) per visualizzare i volumi dell'array di storage raggruppati per carico di lavoro e il tipo di applicazione a cui è associato il carico di lavoro.
* È possibile selezionare la scheda applicazioni e carichi di lavoro nel riquadro prestazioni per visualizzare le metriche delle performance (latenza, IOPS e MB) per gli oggetti logici. Gli oggetti sono raggruppati in base all'applicazione e al carico di lavoro associato. Raccogliendo questi dati sulle performance a intervalli regolari, è possibile stabilire misurazioni di riferimento e analizzare i trend, che possono aiutare a indagare i problemi relativi alle performance di i/O.

