---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-storage-array-passwords.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Aggiornare le password utilizzate per la visualizzazione e l"accesso agli array di storage nel plug-in Storage per vCenter.' 
---
= Modificare le password degli array di storage
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiornare le password utilizzate per visualizzare e accedere agli array di storage nel plug-in Storage per vCenter.

.Prima di iniziare
È necessario conoscere la password corrente per lo storage array, impostata in System Manager.

.A proposito di questa attività
In questa attività, immettere la password corrente per un array di storage in modo da potervi accedere nel plug-in. Questo potrebbe essere necessario se la password dell'array è stata modificata in System Manager.

.Fasi
. Dalla pagina *Manage* (Gestisci), selezionare uno o più array di storage.
. Selezionare menu:operazioni non comuni[fornire password array di storage].
. Immettere la password o le password per ciascun array di storage, quindi fare clic su *Save* (Salva).

