---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-enable-security-for-a-pool-or-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'È possibile attivare Drive Security per un pool o un gruppo di volumi per impedire l"accesso non autorizzato ai dati sulle unità contenute nel pool o nel gruppo di volumi.' 
---
= Abilitare la protezione per un pool o un gruppo di volumi
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile attivare Drive Security per un pool o un gruppo di volumi per impedire l'accesso non autorizzato ai dati sulle unità contenute nel pool o nel gruppo di volumi.

L'accesso in lettura e scrittura per i dischi è disponibile solo attraverso un controller configurato con una chiave di sicurezza.

.Prima di iniziare
* La funzione Drive Security deve essere attivata.
* È necessario creare una chiave di sicurezza.
* Il pool o il gruppo di volumi deve trovarsi in uno stato ottimale.
* Tutti i dischi del pool o del gruppo di volumi devono essere dischi sicuri.


.A proposito di questa attività
Se si desidera utilizzare Drive Security, selezionare un pool o un gruppo di volumi che supporti la protezione. Un pool o un gruppo di volumi può contenere dischi sicuri e non sicuri, ma tutti i dischi devono essere sicuri per poter utilizzare le proprie funzionalità di crittografia.

Una volta attivato il sistema di protezione, è possibile rimuoverlo solo eliminando il pool o il gruppo di volumi, quindi cancellando i dischi.

.Fasi
. Nella pagina Manage (Gestione), selezionare l'array di storage con il pool o il gruppo di volumi.
. Selezionare menu:Provisioning[Configure Pools and Volume Groups] (Configura pool e gruppi di volumi).
. Selezionare il pool o il gruppo di volumi in cui si desidera attivare la protezione, quindi fare clic su menu:More[Enable Security] (Altro[attiva protezione]).
+
Viene visualizzata la finestra di dialogo Conferma abilitazione protezione.

. Confermare che si desidera attivare la protezione per il pool o il gruppo di volumi selezionato, quindi fare clic su *Enable* (attiva).

