---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-host-or-host-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: È possibile rimuovere un host o un cluster di host in modo che i volumi non siano più associati a tale host. 
---
= Elimina un cluster host o host in plugin storage SANtricity per vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere un host o un cluster di host in modo che i volumi non siano più associati a tale host.

.A proposito di questa attività
Tenere presenti queste linee guida quando si elimina un host o un cluster host:

* Tutte le assegnazioni di volume specifiche vengono eliminate e i volumi associati sono disponibili per una nuova assegnazione.
* Se l'host fa parte di un cluster host che dispone di assegnazioni specifiche, il cluster host non viene influenzato. Tuttavia, se l'host fa parte di un cluster di host che non ha altre assegnazioni, il cluster di host e qualsiasi altro host o identificativo di porta host associato ereditano eventuali assegnazioni predefinite.
* Tutti gli identificatori di porta host associati all'host diventano indefiniti.


.Fasi
. Dalla pagina Manage (Gestione), selezionare lo storage array con la connessione host.
. Selezionare menu:Provisioning[Configure hosts] (Configura host).
+
Viene visualizzata la pagina Configure hosts (Configura host).

. Selezionare l'host o il cluster host che si desidera eliminare, quindi fare clic su *Delete* (Elimina).
+
Viene visualizzata la finestra di dialogo di conferma.

. Confermare che si desidera eseguire l'operazione, quindi fare clic su *Delete* (Elimina).


.Risultati
Se si elimina un host, il sistema esegue le seguenti operazioni:

* Elimina l'host e, se applicabile, lo rimuove dal cluster host.
* Rimuove l'accesso a tutti i volumi assegnati.
* Riporta i volumi associati a uno stato non assegnato.
* Restituisce gli identificatori di porta host associati all'host a uno stato non associato. Se si elimina un cluster host, il sistema esegue le seguenti operazioni:
+
** Elimina il cluster host e gli host associati (se presenti).
** Rimuove l'accesso a tutti i volumi assegnati.
** Riporta i volumi associati a uno stato non assegnato.
** Restituisce gli identificatori di porta host associati agli host a uno stato non associato.



