---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-clear-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: È possibile rimuovere il software del sistema operativo in fasi per assicurarsi che una versione in sospeso non venga attivata inavvertitamente in un secondo momento. 
---
= Software del sistema operativo suddiviso in fasi chiaro nel plug-in di storage SANtricity per vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere il software del sistema operativo in fasi per assicurarsi che una versione in sospeso non venga attivata inavvertitamente in un secondo momento. La rimozione del software del sistema operativo in fasi non influisce sulla versione corrente in esecuzione sugli array di storage.

.Fasi
. Dalla vista principale, selezionare *Gestisci*, quindi selezionare menu:Centro di aggiornamento[Cancella software SANtricity in fasi].
+
Viene visualizzata la finestra di dialogo Cancella software SANtricity a fasi che elenca tutti i sistemi storage rilevati con software o NVSRAM in sospeso.

. Se necessario, filtrare o ordinare i sistemi di storage nell'elenco, in modo da poter visualizzare tutti i sistemi che dispongono di software in fasi.
. Selezionare le caselle di controllo relative ai sistemi storage con software in sospeso che si desidera eliminare.
. Fare clic su *Cancella*.
+
Lo stato dell'operazione viene visualizzato nella finestra di dialogo.


