---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-rename-storage-array-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Modificare il nome di un gruppo di array di storage quando il nome corrente non è più significativo o applicabile. 
---
= Rinomina un gruppo di storage array in plugin storage SANtricity per vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile modificare il nome di un gruppo di array di storage quando il nome corrente non è più significativo o applicabile.

.A proposito di questa attività
Tenere presenti queste linee guida.

* Un nome può essere composto da lettere, numeri e caratteri speciali come sottolineatura (_), trattino (-) e cancelletto ( n.). Se si sceglie un altro carattere, viene visualizzato un messaggio di errore. Viene richiesto di scegliere un altro nome.
* Limitare il nome a 30 caratteri. Gli spazi iniziali e finali del nome vengono cancellati.
* Utilizzare un nome univoco e significativo, facile da comprendere e ricordare.
* Evitare nomi o nomi arbitrari che perderebbero rapidamente il loro significato in futuro.


.Fasi
. Dalla vista principale, selezionare *Gestisci*, quindi selezionare il gruppo di array di storage che si desidera rinominare.
. Selezionare menu:Manage Groups[Rename storage array group] (Gestisci gruppi[Rinomina gruppo array di storage])
. Nel campo *Nome gruppo*, digitare un nuovo nome per il gruppo.
. Fare clic su *Rinomina*.

