---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Il provisioning delle risorse è una funzionalità disponibile negli array di storage EF300 e EF600, che consente di utilizzare immediatamente i volumi senza alcun processo di inizializzazione in background. 
---
= Cosa occorre sapere sulla funzionalità dei volumi con provisioning delle risorse?
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il provisioning delle risorse è una funzionalità disponibile negli array di storage EF300 e EF600, che consente di utilizzare immediatamente i volumi senza alcun processo di inizializzazione in background.


NOTE: La funzionalità di provisioning delle risorse non è al momento disponibile. In alcune viste, i componenti potrebbero essere segnalati come capaci di provisioning delle risorse, ma la capacità di creare volumi con provisioning delle risorse è stata disattivata fino a quando non sarà possibile riattivarli in un aggiornamento futuro.



== Volumi con provisioning delle risorse

Un volume con provisioning di risorse è un volume denso in un gruppo di volumi o pool SSD, in cui la capacità del disco viene allocata (assegnata al volume) quando viene creato il volume, ma i blocchi disco vengono disallocati (non mappati). Per confronto, in un volume thick tradizionale, tutti i blocchi di dischi vengono mappati o allocati durante un'operazione di inizializzazione del volume in background per inizializzare i campi di informazioni di protezione Data Assurance e rendere i dati e la parità RAID coerenti in ogni stripe RAID. Con un volume con provisioning di risorse, non è prevista alcuna inizializzazione in background con time-bound. Al contrario, ogni stripe RAID viene inizializzata alla prima scrittura su un blocco di volume nello stripe.

I volumi con provisioning delle risorse sono supportati solo su gruppi di volumi e pool SSD, in cui tutti i dischi del gruppo o del pool supportano la funzionalità di ripristino degli errori NVMe Deallocated o Unwritten Logical Block Error Enable (DULBE). Quando viene creato un volume con provisioning di risorse, tutti i blocchi di dischi assegnati al volume vengono deallocati (non mappati). Inoltre, gli host possono deallocare i blocchi logici nel volume utilizzando il comando NVMe Dataset Management. La deallocazione dei blocchi può migliorare la durata dell'utilizzo degli SSD e aumentare le massime prestazioni di scrittura. Il miglioramento varia in base al modello e alla capacità di ciascun disco.



== Attivazione e disattivazione della funzione

Il provisioning delle risorse è attivato per impostazione predefinita nei sistemi in cui i dischi supportano DULBE. È possibile disattivare l'impostazione predefinita da Pools & Volume Groups. La disattivazione del provisioning delle risorse è un'azione permanente per i volumi esistenti e non può essere annullata (ad esempio, non è possibile riattivare il provisioning delle risorse per questi gruppi di volumi e pool).

Tuttavia, se si desidera riattivare il provisioning delle risorse per i nuovi volumi creati, è possibile farlo dal menu:Impostazioni[sistema]. Tenere presente che quando si riattiva il provisioning delle risorse, vengono influenzati solo i gruppi di volumi e i pool appena creati. Tutti i gruppi di volumi e i pool esistenti rimarranno invariati. Se lo si desidera, è anche possibile disattivare nuovamente il provisioning delle risorse dal menu:Impostazioni[sistema].
