---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: È possibile visualizzare statistiche nominali e statistiche dettagliate per la cache SSD. 
---
= Come si visualizzano e interpretano tutte le statistiche della cache SSD?
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile visualizzare statistiche nominali e statistiche dettagliate per la cache SSD.

Le statistiche nominali sono un sottoinsieme delle statistiche dettagliate. Le statistiche dettagliate possono essere visualizzate solo quando si esportano tutte le statistiche SSD in un file .csv. Durante la revisione e l'interpretazione delle statistiche, tenere presente che alcune interpretazioni derivano da una combinazione di statistiche.



=== Statistiche nominali

Per visualizzare le statistiche della cache SSD, accedere alla pagina *Manage* (Gestione). Selezionare menu:Provisioning[Configure Pools & Volume Groups] (Configura pool e gruppi di volumi). Selezionare la cache SSD per cui si desidera visualizzare le statistiche, quindi selezionare menu:More[View Statistics] (Visualizza statistiche). Le statistiche nominali vengono visualizzate nella finestra di dialogo View SSD cache Statistics (Visualizza statistiche cache SSD).


NOTE: Questa funzione non è disponibile sui sistemi storage EF600 o EF300.

L'elenco include le statistiche nominali, che sono un sottoinsieme delle statistiche dettagliate.



=== Statistiche dettagliate

Le statistiche dettagliate sono costituite dalle statistiche nominali e da statistiche aggiuntive. Queste statistiche aggiuntive vengono salvate insieme alle statistiche nominali, ma a differenza delle statistiche nominali, non vengono visualizzate nella finestra di dialogo View SSD cache Statistics (Visualizza statistiche cache SSD). È possibile visualizzare le statistiche dettagliate solo dopo aver esportato le statistiche in un file .csv.

Le statistiche dettagliate sono elencate dopo le statistiche nominali.
