---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-why-are-some-drives-not-showing-up.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Nella finestra di dialogo Add Capacity (Aggiungi capacità), non tutti i dischi sono disponibili per l"aggiunta di capacità a un pool o a un gruppo di volumi esistente.' 
---
= Perché alcuni dischi non vengono visualizzati?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nella finestra di dialogo Add Capacity (Aggiungi capacità), non tutti i dischi sono disponibili per l'aggiunta di capacità a un pool o a un gruppo di volumi esistente.

I dischi non sono idonei per uno dei seguenti motivi:

* Un disco deve essere non assegnato e non abilitato alla sicurezza. I dischi già parte di un altro pool, di un altro gruppo di volumi o configurati come hot spare non sono idonei. Se un disco non è assegnato ma è abilitato per la protezione, è necessario cancellarlo manualmente affinché sia idoneo.
* Un disco in uno stato non ottimale non è idoneo.
* Se la capacità di un disco è troppo piccola, non è idonea.
* Il tipo di disco deve corrispondere all'interno di un pool o di un gruppo di volumi. Non è possibile combinare i seguenti elementi:
+
** Dischi rigidi (HDD) con dischi a stato solido (SSD)
** NVMe con unità SAS
** Dischi con blocchi di volumi da 512 byte e 4 KiB


* Se un pool o un gruppo di volumi contiene tutti i dischi con funzionalità di protezione, i dischi con funzionalità di protezione non sono elencati.
* Se un pool o un gruppo di volumi contiene tutti i dischi FIPS (Federal Information Processing Standard), i dischi non FIPS non sono elencati.
* Se un pool o un gruppo di volumi contiene tutte le unità compatibili con Data Assurance (da) e nel pool o nel gruppo di volumi è presente almeno un volume abilitato da, un'unità che non supporta da non è idonea, quindi non può essere aggiunta a tale pool o gruppo di volumi. Tuttavia, se nel pool o nel gruppo di volumi non è presente alcun volume abilitato da, è possibile aggiungere un'unità che non supporta da a a tale pool o gruppo di volumi. Se si decide di combinare questi dischi, tenere presente che non è possibile creare volumi abilitati da.



NOTE: È possibile aumentare la capacità dell'array di storage aggiungendo nuove unità o eliminando pool o gruppi di volumi.
