---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-alert-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Importa configurazioni di avviso da uno storage array ad altri storage array. 
---
= Importare le impostazioni degli avvisi in plugin di archiviazione SANtricity per vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile importare configurazioni di avviso da uno storage array ad altri storage array. Questa operazione batch consente di risparmiare tempo quando è necessario configurare più array nella rete.

.Prima di iniziare
Assicurarsi che:

* Gli avvisi vengono configurati in System Manager (menu:Impostazioni[Avvisi]) per lo storage array che si desidera utilizzare come origine.
* Il backup della configurazione esistente per gli array di storage di destinazione viene eseguito in System Manager (menu:Impostazioni[sistema > Salva configurazione array di storage]).
* Sono stati esaminati i requisiti per la replica delle configurazioni di storage in link:vc-olh-import-settings-overview.html["Panoramica delle impostazioni di importazione"].


.A proposito di questa attività
È possibile selezionare avvisi e-mail, SNMP o syslog per l'operazione di importazione:

* *Avvisi via email* -- Indirizzo del server di posta e indirizzi email dei destinatari degli avvisi.
* *Syslog alerts* -- un indirizzo del server syslog e una porta UDP.
* *SNMP alerts* -- Nome di comunità e indirizzo IP per il server SNMP.


.Fasi
. Dalla pagina Manage (Gestione), fare clic su menu:Actions[Import Settings] (azioni[Impostazioni importazione]).
+
Viene visualizzata la procedura guidata Import Settings (Impostazioni importazione).

. Nella finestra di dialogo Select Settings (Seleziona impostazioni), selezionare *Email alerts* (Avvisi email), *SNMP alerts* (Avvisi SNMP) o *Syslog alerts* (Avvisi Syslog), quindi fare clic su *Next* (Avanti).
+
Viene visualizzata una finestra di dialogo per la selezione dell'array di origine.

. Nella finestra di dialogo Select Source (Seleziona origine), selezionare l'array con le impostazioni che si desidera importare, quindi fare clic su *Next* (Avanti).
. Nella finestra di dialogo Select targets (Seleziona destinazioni), selezionare uno o più array per ricevere le nuove impostazioni.
+

NOTE: Gli array di storage con firmware inferiore a 8.50 non sono disponibili per la selezione. Inoltre, un array non viene visualizzato in questa finestra di dialogo se il plug-in non è in grado di comunicare con tale array (ad esempio, se non è in linea o se presenta problemi di certificato, password o rete).

. Fare clic su *fine*.
+
La pagina Operations (operazioni) visualizza i risultati dell'operazione di importazione. Se l'operazione non riesce, fare clic sulla relativa riga per visualizzare ulteriori informazioni.



.Risultato
Gli array di storage di destinazione sono ora configurati per inviare avvisi agli amministratori tramite e-mail, SNMP o syslog.
