---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-do-application-specific-workloads-help-me-manage-my-storage-array.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Le caratteristiche del volume del carico di lavoro specifico dell"applicazione determinano il modo in cui il carico di lavoro interagisce con i componenti dell"array di storage e aiutano a determinare le performance dell"ambiente in una determinata configurazione.' 
---
= In che modo i carichi di lavoro specifici dell'applicazione mi aiutano a gestire lo storage array?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le caratteristiche del volume del carico di lavoro specifico dell'applicazione determinano il modo in cui il carico di lavoro interagisce con i componenti dell'array di storage e aiutano a determinare le performance dell'ambiente in una determinata configurazione.

Un'applicazione è un software come SQL Server o Exchange. È possibile definire uno o più workload per supportare ciascuna applicazione. Per alcune applicazioni, il sistema consiglia automaticamente una configurazione del volume che ottimizzi lo storage. Caratteristiche come il tipo di i/o, la dimensione del segmento, la proprietà del controller e la cache di lettura e scrittura sono incluse nella configurazione del volume.
