---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-automatically.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: È possibile creare pool automaticamente quando il sistema rileva almeno 11 dischi non assegnati o rileva un disco non assegnato idoneo per un pool esistente. 
---
= Crea pool automaticamente
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare pool automaticamente quando il sistema rileva almeno 11 dischi non assegnati o rileva un disco non assegnato idoneo per un pool esistente. Un pool è un insieme di dischi raggruppati in modo logico.

.Prima di iniziare
È possibile avviare la finestra di dialogo Configurazione automatica pool quando si verifica una delle seguenti condizioni:

* È stato rilevato almeno un disco non assegnato che può essere aggiunto a un pool esistente con tipi di disco simili.
* Sono stati rilevati undici (11) o più dischi non assegnati che possono essere utilizzati per creare un nuovo pool (se non possono essere aggiunti a un pool esistente a causa di tipi di dischi diversi).


.A proposito di questa attività
È possibile utilizzare la creazione automatica del pool per configurare facilmente tutte le unità non assegnate nell'array di storage in un unico pool e per aggiungere unità nei pool esistenti.

Tenere presente quanto segue:

* Quando si aggiungono dischi a un array di storage, il sistema rileva automaticamente i dischi e richiede di creare un singolo pool o più pool in base al tipo di disco e alla configurazione corrente.
* Se i pool sono stati precedentemente definiti, il sistema richiede automaticamente di aggiungere le unità compatibili a un pool esistente. Quando vengono aggiunte nuove unità a un pool esistente, il sistema ridistribuisce automaticamente i dati nella nuova capacità, che ora include le nuove unità aggiunte.
* Quando si configura uno storage array EF600 o EF300, assicurarsi che ciascun controller abbia accesso a un numero uguale di dischi nei primi 12 slot e a un numero uguale di dischi negli ultimi 12 slot. Questa configurazione aiuta i controller a utilizzare entrambi i bus PCIe lato disco in modo più efficace. Per la creazione del pool, è necessario utilizzare tutti i dischi dell'array di storage.


.Fasi
. Nella pagina Manage (Gestione), selezionare l'array di storage per il pool.
. Selezionare menu:Provisioning[Configure Pools and Volume Groups] (Configura pool e gruppi di volumi).
. Selezionare menu:More[Avvia configurazione automatica del pool].
+
La tabella dei risultati elenca i nuovi pool, i pool esistenti con le unità aggiunte o entrambi. Per impostazione predefinita, un nuovo pool viene denominato con un numero sequenziale.

+
Si noti che il sistema esegue le seguenti operazioni:

+
** Crea un singolo pool se il numero di dischi con lo stesso tipo di disco (HDD o SSD) è sufficiente e la capacità è simile.
** Crea più pool se la capacità non assegnata è costituita da diversi tipi di dischi.
** Aggiunge le unità a un pool esistente se un pool è già definito nell'array di storage e si aggiungono nuove unità dello stesso tipo di disco al pool.
** Aggiunge le unità dello stesso tipo di unità al pool esistente e utilizza gli altri tipi di unità per creare pool diversi se le nuove unità sono di tipi diversi di unità.


. Per modificare il nome di un nuovo pool, fare clic sull'icona *Modifica* (la matita).
. Per visualizzare ulteriori caratteristiche del pool, posizionare il cursore o toccare l'icona Dettagli (la pagina).
+
Vengono visualizzate informazioni relative al tipo di disco, alla funzionalità di sicurezza, alla funzione di data assurance (da), alla protezione contro la perdita di shelf e alla protezione contro la perdita di cassetto.

+
Per gli array di storage EF600 e EF300, vengono visualizzate anche le impostazioni relative al provisioning delle risorse e alle dimensioni dei blocchi di volume.

. Fare clic su *Accept* (Accetta).

