---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-trusted-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Eliminare uno o più certificati non più necessari. 
---
= Elimina i certificati attendibili nel plug-in di archiviazione SANtricity per vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile eliminare uno o più certificati non più necessari, ad esempio un certificato scaduto.

.Prima di iniziare
Importare il nuovo certificato prima di eliminarlo.


CAUTION: Tenere presente che l'eliminazione di un certificato root o intermedio può influire su più array di storage, poiché questi array possono condividere gli stessi file di certificato.

.Fasi
. Selezionare *Certificate Management* (Gestione certificati).
. Selezionare la scheda *Trusted*.
. Selezionare uno o più certificati nella tabella, quindi fare clic su *Elimina*.
+

NOTE: La funzione Elimina non è disponibile per i certificati preinstallati.

+
Viene visualizzata la finestra di dialogo Conferma eliminazione certificato attendibile.

. Confermare l'eliminazione, quindi fare clic su *Delete* (Elimina).
+
Il certificato viene rimosso dalla tabella.


