---
permalink: maintenance-e5700/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E5700 host interface card, E5700 HIC, replace E5700 HIC, failed E5700 HIC 
summary: Esaminare i requisiti per la sostituzione HIC E5700. 
---
= Requisiti per la sostituzione HIC E5700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiungere, aggiornare o sostituire una scheda di interfaccia host (HIC) in un E5700, esaminare i requisiti e le considerazioni.



== Panoramica della procedura

È possibile aggiungere, aggiornare o sostituire un HIC nello shelf del controller E5724 e nello shelf del controller E5760.

Di seguito è riportata una panoramica dei passaggi per la sostituzione di un HIC in un controller E5700 (E5724 o E5760):

. Portare il controller offline
. Rimuovere il contenitore del controller
. Sostituire la batteria
. Sostituire il contenitore del controller
. Portare il controller online




== Requisiti per l'aggiunta, l'aggiornamento o la sostituzione di un HIC

Se si intende aggiungere, aggiornare o sostituire una scheda di interfaccia host (HIC), tenere presenti i seguenti requisiti.

* È necessario pianificare una finestra di manutenzione dei tempi di inattività per questa procedura. Quando si installa HICS, l'alimentazione deve essere spenta, in modo che non sia possibile accedere ai dati sullo storage array fino a quando non si è completata correttamente questa procedura. (In una configurazione duplex, questo perché entrambi i controller devono avere la stessa configurazione HIC quando vengono accesi).
* È necessario disporre di due HICS compatibili con i controller.
+
Per le configurazioni duplex (due controller), l'HICS installato nei due contenitori del controller deve essere identico. La presenza di HICS non corrispondenti causa il blocco del controller con l'HIC sostitutivo quando lo si porta online.

* Sono disponibili tutti i cavi, i ricetrasmettitori, gli switch e gli HBA (host Bus Adapter) necessari per collegare le nuove porte host.
+
Per informazioni sull'hardware compatibile, fare riferimento a. https://mysupport.netapp.com/NOW/products/interoperability["Matrice di interoperabilità NetApp"^] o il http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^].

* Si dispone di un braccialetto ESD o si sono prese altre precauzioni antistatiche.
* Hai un cacciavite Phillips n. 1.
* Sono presenti etichette per identificare ciascun cavo collegato al contenitore del controller.
* Si dispone di una stazione di gestione con un browser in grado di accedere a Gestore di sistema SANtricity per il controller. Per aprire l'interfaccia di System Manager, puntare il browser sul nome di dominio o sull'indirizzo IP del controller.

