---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: 'Verifica dei requisiti per l"aggiornamento e la sostituzione dei controller e-Series.' 
---
= Considerazioni sull'upgrade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare i controller, esaminare le seguenti considerazioni.


NOTE: Per informazioni specifiche sulle configurazioni supportate da ciascun controller e-Series, fai riferimento al https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models["Panoramica dell'hardware e-Series"].



== Requisiti hardware e firmware

* *Aggiornamenti dei controller duplex e simplex*
+
Per i vassoi del disco del controller duplex, sostituire entrambi i controller. Per i vassoi del disco del controller simplex, sostituire il controller singolo. In entrambi i casi, è necessario spegnere il vassoio del disco del controller Di conseguenza, non è possibile accedere ai dati sull'array di storage fino a quando la sostituzione non viene completata correttamente.

* *Vassoi e shelf*
+
Generalmente, gli storage array con uno shelf di controller e-Series vengono gestiti tramite l'interfaccia utente di SANtricity System Manager.

* *Batterie del controller*
+
Un nuovo controller viene spedito senza una batteria installata. Quando possibile, rimuovere la batteria dal vecchio controller e installarla nel nuovo controller. Tuttavia, per alcuni aggiornamenti del controller, la batteria del vecchio controller non è compatibile con il nuovo controller. In questi casi, è necessario ordinare una batteria insieme al nuovo controller e tenere la batteria a disposizione prima di iniziare queste attività.

* *Mirroring sincrono e mirroring asincrono*
+
Se lo storage array partecipa al mirroring sincrono, tra il sito primario e il sito remoto sono supportate solo le connessioni iSCSI o Fibre Channel. Se la configurazione della scheda di interfaccia host (HIC) nei nuovi controller non include connessioni iSCSI o Fibre Channel, il mirroring sincrono non sarà supportato.

+
Per il mirroring asincrono, l'array di storage locale e l'array di storage remoto possono eseguire diverse versioni del firmware. La versione minima del firmware supportata è la versione 7.84 del firmware SANtricity.




NOTE: Per i controller E4000, il mirroring è supportato solo sulle connessioni Fibre Channel.

* *Limiti degli oggetti di storage*
+
Se si modificano i controller dai modelli midrange a quelli entry-level (ad esempio, modelli 5x00 a modelli 2x00), la nuova configurazione degli array di storage supporterà un numero inferiore di alcuni oggetti di storage (ad esempio, volumi) nel software di gestione dello storage rispetto alla vecchia configurazione. Assicurarsi che la vecchia configurazione non superi i limiti degli oggetti di storage.

+
Per ulteriori informazioni, vedere http://hwu.netapp.com/home.aspx["Hardware Universe"^] .

* *Aggiornamento a modelli più recenti*
+
Se si stanno sostituendo i controller per eseguire l'aggiornamento a un nuovo modello, tenere presente che lo storage array attuale potrebbe disporre di funzionalità premium installate che il nuovo modello non è in grado di supportare.

+
Durante l'upgrade del controller e-Series, dovresti disabilitare tutte le funzionalità premium utilizzate sullo storage array non supportate sui nuovi controller.

* *Gestione in banda utilizzando il volume di accesso*
+
** E4000 non supporta la gestione in banda utilizzando il volume di accesso.
+
Prima di eseguire l'aggiornamento a E4000 controller, rimuovere la mappatura del volume di accesso da tutti gli host e i cluster host definiti.







== Compatibilità con gli aggiornamenti

Esaminare i percorsi di aggiornamento supportati per ciascun modello di array di storage.

[role="tabbed-block"]
====
.Compatibilità di aggiornamento del controller E4000
--
[cols="h,d,d,d"]
|===
| Percorso di aggiornamento | Batteria | Supporto delle funzioni | Shelf SAS-3 


| Da E2800 a E4000  a| 
Ordinare una nuova batteria.
 a| 
* E4000 non supporta ARVM iSCSI
* La porta baseboard E4000 è solo iSCSI e non può essere modificata in FC
* E4000 può supportare solo dischi da 300 TB
* E4000 può supportare solo volumi 512
* E4000 non supporta le configurazioni SAS
* E4000 non supporta i volumi di archiviazione remota
* E4000 non supporta la gestione in banda utilizzando il volume di accesso.

 a| 
I controller E4000 devono utilizzare shelf SAS-3.



| Da E5700 a E4000  a| 
Ordinare una nuova batteria.
 a| 
* E4000 non supporta ARVM iSCSI
* La porta baseboard E4000 è solo iSCSI e non può essere modificata in FC
* E4000 può supportare solo dischi da 300 TB
+
** E5700 può supportare fino a 480 dischi


* E4000 può supportare solo volumi 512
+
** E5700 supporta fino a 2048 volumi


* Il supporto della scheda di interfaccia host InfiniBand non è disponibile
* E4000 non supporta le configurazioni SAS
* E4000 non supporta i volumi di archiviazione remota
* E4000 non supporta la gestione in banda utilizzando il volume di accesso.

 a| 
I controller E4000 devono utilizzare shelf SAS-3.

|===
--
.Compatibilità con l'aggiornamento dei controller EF600 e EF300
--
[cols="h,d,d,d"]
|===
| Percorso di aggiornamento | Batteria | Supporto delle funzioni | Shelf SAS-3 


| Da EF600 a EF600 con una diversa scheda di interfaccia host  a| 
Riutilizzare la vecchia batteria.
 a| 
* Nessun supporto per i volumi con thin provisioning
* Nessun supporto mirroring sincrono

| I controller EF600 devono utilizzare shelf SAS-3. 


| Da EF300 a EF600  a| 
Riutilizzare la vecchia batteria.
 a| 
* Nessun supporto per i volumi con thin provisioning
* Nessun supporto mirroring sincrono

 a| 
I controller EF600 devono utilizzare shelf SAS-3.

|===
--
.Compatibilità con gli aggiornamenti dei controller legacy
--
[cols="h,d,d,d,d"]
|===
| Percorso di aggiornamento | Batteria | ID fornitore | Supporto delle funzioni | Shelf SAS-3 


| Da E2x00 a E2x00  a| 
Riutilizzare la vecchia batteria.
 a| 
Sono necessarie ulteriori operazioni.
 a| 
Gli snapshot legacy non sono supportati su E2700.
 a| 
I controller E2800 non devono essere posizionati negli shelf SAS-2.



| Da E2x00 a E5x00  a| 
Ordinare una nuova batteria.
 a| 
È necessario eseguire ulteriori operazioni quando si esegue l'aggiornamento da E2600 a E5500 o E5600 o quando si esegue l'aggiornamento da E2700 a E5400.
 a| 
* Gli snapshot legacy non sono supportati su E5500 o E5600.
* Il mirroring remoto dei volumi legacy (RVM) non è supportato su E5500 o E5600 con iSCSI HICS.
* Data Assurance non è supportato su E5500 o E5600 con iSCSI HICS.
* I controller E5700 non devono essere posizionati negli shelf SAS-2.

 a| 
I controller E5400, E5500 e E5600 non devono essere posizionati negli shelf SAS-3.



| Da E5x00 a E2x00  a| 
Ordinare una nuova batteria.
 a| 
È necessario eseguire ulteriori operazioni quando si esegue l'aggiornamento da E5500 o E5600 a E2600 o quando si esegue l'aggiornamento da E5400 a E2700.
 a| 
Gli snapshot legacy non sono supportati su E2700.
 a| 
I controller 5400, E5500 e E5600 non devono essere posizionati negli shelf SAS-3.



| Da E5x00 a E5x00  a| 
Riutilizzare la vecchia batteria.
 a| 
È necessario eseguire ulteriori operazioni quando si esegue l'aggiornamento da E5400 a E5500 o E5600.
 a| 
* Gli snapshot legacy non sono supportati su E5500 o E5600.
* Il mirroring remoto dei volumi legacy (RVM) non è supportato su E5400 o E5500 con iSCSI HICS.
* Data Assurance non è supportato su E5400 o E5500 con iSCSI HICS.
* I controller E5700 non devono essere posizionati negli shelf SAS-2.

 a| 
I controller E5400, E5500 e E5600 non devono essere posizionati negli shelf SAS-3.



| Da EF5x0 a EF5x0  a| 
Riutilizzare la vecchia batteria.
 a| 
È necessario eseguire ulteriori operazioni quando si esegue l'aggiornamento da EF540 a EF550 o EF560.
 a| 
* Nessuna snapshot legacy per EF550/EF560.
* Nessuna Data Assurance per EF550/EF560 con iSCSI.
* I controller EF570 non devono essere posizionati negli shelf SAS-3.

 a| 
I controller EF540, EF550 e EF560 non devono essere posizionati negli shelf SAS-3.

|===
--
====


== Enclosure SAS

E5700 supporta enclosure SAS-2 DE5600 e DE6600 tramite upgrade della testina. Quando un controller E5700 viene installato in enclosure SAS-2, il supporto per le porte host di base viene disattivato.

|===
| Shelf SAS-2 | Shelf SAS-3 


 a| 
Gli shelf SAS-2 includono i seguenti modelli:

* Tray di dischi DE1600, DE5600 e DE6600
* Tray di dischi controller E5400, E5500 e E5600
* Array flash EF540, EF550 e EF560
* Tray di dischi controller E2600 e E2700

 a| 
Gli shelf SAS-3 includono i seguenti modelli:

* Shelf di controller E4000
* EF600 ripiani controller ^1^
* EF300 ripiani controller ^1^
* Shelf di controller E2800
* Shelf di controller E5700
* Shelf di dischi DE212C, DE224C, DE460C


|===
Note:

. I controller EF600 e EF300 possono utilizzare solo shelf SAS-3 come espansione.




== Protezione dell'investimento da SAS-2 a SAS-3

È possibile riconfigurare il sistema SAS-2 per l'utilizzo dietro un nuovo shelf di controller SAS-3 (E57XX/EF570/E28XX).


NOTE: Questa procedura richiede una richiesta di variazione del prodotto (FPVR). Per presentare un FPVR, contatta il tuo team di vendita.
