---
permalink: upgrade-controllers/remount-volumes-lsi-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, remount volume, upgrade LSI, vendor ID 
summary: 'Se l"aggiornamento del controller comporta la modifica dell"ID vendor da LSI a NETAPP, i volumi vengono rimontati.' 
---
= Rimontare i volumi dopo aver cambiato il vendor da LSI a NETAPP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'aggiornamento del controller comporta la modifica dell'ID vendor da LSI a NETAPP, seguire la procedura appropriata per il tipo di host:

* <<Rimontare i volumi su un host AIX>>
* <<Rimontare i volumi su un host VMware>>
* <<Rimontare i volumi su un host Windows>>




== Rimontare i volumi su un host AIX

Dopo aver sostituito i controller, è possibile osservare che l'host mostra i nuovi volumi sull'array di storage, ma mostra anche i volumi originali come guasti.

.Fase
Se vengono visualizzati volumi guasti, eseguire `cfgmgr` comando.



== Rimontare i volumi su un host VMware

Dopo aver sostituito i controller, si potrebbero osservare le seguenti condizioni:

* VMware mostra nuovi percorsi per i volumi sull'array di storage, ma mostra anche i percorsi originali come percorsi morti.
* Gli host elencano ancora i volumi sull'array di storage come se disponessi di ID vendor LSI. Questo potrebbe verificarsi quando i volumi sono stati rivendicati dalla regola LSI all'inizio e quindi continuano a utilizzare la stessa regola LSI quando i volumi tornano in linea.
* Il nome visualizzato non riflette la modifica da LSI a NetApp. Questo potrebbe verificarsi perché il nome visualizzato è diventato test libero dopo il rilevamento iniziale. In questo caso, è possibile modificare manualmente il nome visualizzato.


.Fasi
. Eseguire una nuova scansione su ciascun host.
. Arrestare tutte le operazioni di i/o host per questo sottosistema.
. Recuperare i volumi in base alla regola NetApp.
+
.. Eseguire `esxcli storage core device list` comando. Controllare l'output del comando per identificare i volumi i cui nomi hanno il form `aa.xxxx`.
.. Eseguire il comando `do esxcli storage core claiming reclaim -d naa.xxxxx` Per modificare l'ID vendor LSI in NetApp.






== Rimontare i volumi su un host Windows

Dopo aver sostituito i controller, è necessario eseguire il remount dei volumi su un host Windows per consentire agli host collegati di eseguire operazioni di i/o con i volumi posizionati sull'array di storage aggiornato.

.Fasi
. In *Gestione periferiche*, selezionare *Mostra periferiche nascoste*.
. Per ogni dispositivo SCSI NETAPP elencato in *Gestione periferiche*, fare clic con il pulsante destro del mouse sulla voce e selezionare *Disinstalla*.
+
Se Windows visualizza una finestra di dialogo con un messaggio che indica che è necessario riavviare l'host, completare la disinstallazione di tutti i volumi prima di eseguire la scansione per l'hardware e riavviare.

. Fare clic con il pulsante destro del mouse in *Gestione periferiche*, quindi selezionare *Cerca modifiche hardware*.
. Riavviare l'host.

