---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: Se si stanno aggiornando i controller E2800 ed E5700 e la funzione Drive Security è attivata, è necessario sbloccare manualmente i dischi. 
---
= Sbloccare i dischi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funzione Drive Security di questi controller blocca le unità parzialmente, esternamente o internamente. Se la funzione Drive Security è attivata, è necessario sbloccare manualmente queste unità.

Seguire la procedura appropriata per:

* <<Gestione interna delle chiavi>>
* <<Gestione esterna delle chiavi>>




== Gestione interna delle chiavi

Seguire questi passaggi per la gestione interna delle chiavi quando tutti i dischi sono bloccati.

.A proposito di questa attività
I controller appena scambiati si bloccano con un codice di visualizzazione a sette segmenti *L5*. Questo blocco si verifica quando nessun disco può eseguire la sincronizzazione con codice automatico (ACS). Una volta importata la chiave di sicurezza, ACS riprende e aggiorna i nuovi controller.


NOTE: Se non si utilizza la porta di gestione 1, provare con altri indirizzi IP predefiniti: + Ctrl A port 1: 169.254.128.101 + Ctrl A port 2: 169.254.128.102 + Ctrl B port 1: 169.254.128.101 + Ctrl B port 2: 169.254.128.102

.Fasi
. Effettuare una connessione ethernet diretta e privata tra lo storage array e il laptop o PC del client SANtricity. A tale scopo:
+
.. Utilizzare un cavo ethernet RJ45 per collegare il laptop alla porta di gestione 1 del controller A.
.. Per completare la connessione, potrebbe essere necessario assegnare il laptop a un indirizzo IP nella stessa sottorete del controller A. durante il blocco del controller, il controller A assume per impostazione predefinita l'indirizzo di gestione 169.254.128.101. In questo modo, è possibile assegnare il portatile a una subnet come "169.254.128.201".


. Utilizzando l'indirizzo IP 169.254.128.101 con nome utente *admin* e la password vuota, importare la chiave interna utilizzando il `import storageArray securityKey file` comando CLI, con la chiave di sicurezza salvata da link:prepare-upgrade-controllers-task.html["Preparazione per l'aggiornamento dei controller"]. Per informazioni sull'utilizzo di questo comando, consultare la https://docs.netapp.com/us-en/e-series-cli/index.html["Riferimento all'interfaccia della riga di comando"].
+
*Esempio:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
In alternativa, è possibile importare la chiave interna tramite l'API REST tramite la seguente chiamata: `/storage-systems/{system-id}/security-key/import`



I controller proseguiranno con il processo di sincronizzazione del codice automatico dai dischi e si riavvieranno. Dopo il riavvio, i controller saranno accessibili attraverso la configurazione IP originale.



== Gestione esterna delle chiavi

Seguire questi passaggi per la gestione delle chiavi esterne quando tutti i dischi sono bloccati.

.A proposito di questa attività
I controller appena scambiati si bloccano con un codice di visualizzazione a sette segmenti *L5*. Questo blocco si verifica quando nessun disco può eseguire la sincronizzazione con codice automatico (ACS). Una volta importata la chiave di sicurezza, ACS riprende e aggiorna i nuovi controller.

.Fasi
. Effettuare una connessione ethernet diretta e privata tra lo storage array e il laptop o PC del client SANtricity. A tale scopo:
+
.. Utilizzare un cavo ethernet RJ45 per collegare il laptop alla porta di gestione 1 del controller A.
.. Per completare la connessione, potrebbe essere necessario assegnare il laptop a un indirizzo IP nella stessa sottorete del controller A. durante il blocco del controller, il controller A assume per impostazione predefinita l'indirizzo di gestione 169.254.128.101. In questo modo, è possibile assegnare il portatile a una subnet come "169.254.128.201".


. Utilizzando la chiave di protezione salvata da link:prepare-upgrade-controllers-task.html["Preparazione per l'aggiornamento dei controller"], importare la chiave esterna all'indirizzo IP 169.254.128.101 lasciando vuoto il nome utente *admin* e la password.
+
*Esempio:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
In alternativa, è possibile importare la chiave esterna tramite l'API REST tramite la seguente chiamata: `/storage-systems/{system-id}/security-key/import`

+
I controller proseguiranno con il processo di sincronizzazione del codice automatico dai dischi e si riavvieranno. Dopo il riavvio, i controller saranno accessibili attraverso la configurazione IP originale.

. (Opzionale) se necessario, è possibile reimpostare il codice delle unità eseguendo le seguenti operazioni:
+
*Esempio:* `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


