---
permalink: upgrade-santricity/upgrade-drive-firmware-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: Il firmware dei dischi viene aggiornato per assicurarsi di disporre di tutte le funzionalità più recenti e di correzioni di bug. 
---
= Aggiornamento del firmware dei dischi e-Series ed EF-Series
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per aggiornare il firmware dei dischi, che garantisce di disporre delle ultime funzionalità e correzioni.



== Fase 1: Scaricare i file del firmware del disco

In questa fase, accedere al sito del supporto NetApp per scaricare i file del firmware del disco sul client di gestione.

.Fasi
. In Gestore di sistema di SANtricity, selezionare menu:supporto[Centro di aggiornamento].
. In aggiornamento del firmware del disco, fare clic su *NetApp Support* e accedere al sito NetApp Support.
. Dal sito del supporto tecnico, fare clic sulla scheda *Downloads*, quindi selezionare *Disk Drive & firmware Matrix*.
. Selezionare *e-Series e EF-Series Disk firmware.*
. Seguire le istruzioni visualizzate sullo schermo per scaricare i file.




== Fase 2: Avviare l'aggiornamento del firmware del disco

In questa fase, si aggiorna il firmware dei dischi.

.Prima di iniziare
* Eseguire il backup dei dati utilizzando il backup disk-to-disk, la copia del volume (su un gruppo di volumi non interessato dall'aggiornamento del firmware pianificato) o un mirror remoto.
* Assicurarsi che lo stato dello storage array sia ottimale.
* Assicurarsi che tutti i dischi abbiano uno stato ottimale.
* Assicurarsi che non siano in esecuzione modifiche di configurazione sullo storage array.
* Se i dischi sono in grado di eseguire solo un aggiornamento offline, l'attività di i/o su tutti i volumi associati ai dischi viene interrotta.


.Fasi
. Dal System Manager Upgrade Center (menu:Support[Upgrade Center]), fare clic su *Begin Upgrade* nella sezione "Drive firmware upgrade".
+
Viene visualizzata una finestra di dialogo che elenca i file del firmware del disco attualmente in uso.

. Estrarre (decomprimere) i file scaricati dal sito del supporto.
. Fare clic su *Browse* (Sfoglia) e selezionare i nuovi file del firmware del disco scaricati dal sito di supporto.
+
I file del firmware del disco hanno un nome file simile a. `D_HUC101212CSS600_30602291_MS01_2800_0002` con l'estensione di `.dlp`.

+
È possibile selezionare fino a quattro file del firmware del disco, uno alla volta. Se più di un file del firmware del disco è compatibile con lo stesso disco, viene visualizzato un errore di conflitto del file. Decidere quale file del firmware del disco utilizzare per l'aggiornamento e rimuovere l'altro.

. Fare clic su *Avanti*.
+
Viene visualizzata la finestra di dialogo Select Drives (Seleziona unità), che elenca le unità che è possibile aggiornare con i file selezionati.

+
Vengono visualizzati solo i dischi compatibili.

+
Il firmware selezionato per l'unità viene visualizzato nell'area delle informazioni *firmware proposto*. Se è necessario modificare il firmware, fare clic su *Indietro* per tornare alla finestra di dialogo precedente.

. Selezionare il tipo di aggiornamento che si desidera eseguire:
+
** *Online (impostazione predefinita)* -- Mostra i dischi in grado di supportare il download del firmware _mentre lo storage array sta elaborando i/O. Quando si seleziona questo metodo di aggiornamento, non è necessario interrompere l'i/o dei volumi associati utilizzando questi dischi. Questi dischi vengono aggiornati uno alla volta mentre lo storage array sta elaborando i/o su tali dischi.
** *Offline (Parallel)* -- Mostra i dischi che possono supportare il download del firmware _solo quando l'attività di i/o viene interrotta_ su qualsiasi volume che utilizza i dischi. Quando si seleziona questo metodo di aggiornamento, è necessario interrompere tutte le attività di i/o su tutti i volumi che utilizzano i dischi che si stanno aggiornando. I dischi che non hanno ridondanza devono essere elaborati come operazioni offline. Questo requisito include qualsiasi disco associato alla cache SSD, un gruppo di volumi RAID 0 o qualsiasi pool o gruppo di volumi degradati. L'aggiornamento offline (parallelo) è in genere più rapido rispetto al metodo online (predefinito).


. Nella prima colonna della tabella, selezionare il disco o i dischi che si desidera aggiornare.
. Fare clic su *Start* e confermare che si desidera eseguire l'operazione.
+
Per interrompere l'aggiornamento, fare clic su *Stop*. Tutti i download del firmware attualmente in corso sono stati completati. Tutti i download del firmware non avviati vengono annullati.

+

CAUTION: L'interruzione dell'aggiornamento del firmware del disco potrebbe causare la perdita di dati o la mancata disponibilità dei dischi.

. (Facoltativo) per visualizzare un elenco degli aggiornamenti, fare clic su *Save Log* (Salva registro).
+
Il file viene salvato nella cartella Download del browser con il nome `drive_upgrade_log-timestamp.txt`.

. Se durante la procedura di aggiornamento si verifica uno dei seguenti errori, eseguire l'azione consigliata appropriata.
+
|===
| Se si verifica questo errore di download del firmware... | Quindi procedere come segue... 


 a| 
** Dischi assegnati non riusciti

 a| 
Un motivo del guasto potrebbe essere che il disco non dispone della firma appropriata. Assicurarsi che il disco interessato sia un disco autorizzato. Per ulteriori informazioni, contatta il supporto tecnico.

Quando si sostituisce un'unità, assicurarsi che la capacità dell'unità sostitutiva sia uguale o superiore a quella dell'unità che si sta sostituendo.

È possibile sostituire il disco guasto mentre lo storage array riceve i/O.



 a| 
Controllare l'array di storage
 a| 
** Assicurarsi che a ciascun controller sia stato assegnato un indirizzo IP.
** Assicurarsi che tutti i cavi collegati al controller non siano danneggiati.
** Assicurarsi che tutti i cavi siano collegati saldamente.




 a| 
Dischi hot spare integrati
 a| 
Questa condizione di errore deve essere corretta prima di poter aggiornare il firmware. Avviare System Manager e utilizzare Recovery Guru per risolvere il problema.



 a| 
Gruppi di volumi incompleti
 a| 
Se uno o più gruppi di volumi o pool di dischi sono incompleti, è necessario correggere questa condizione di errore prima di poter aggiornare il firmware. Avviare System Manager e utilizzare Recovery Guru per risolvere il problema.



 a| 
Operazioni esclusive (diverse dai supporti in background/scansione di parità) attualmente in esecuzione su qualsiasi gruppo di volumi
 a| 
Se sono in corso una o più operazioni esclusive, queste devono essere completate prima di poter aggiornare il firmware. Utilizzare System Manager per monitorare l'avanzamento delle operazioni.



 a| 
Volumi mancanti
 a| 
È necessario correggere la condizione del volume mancante prima di poter aggiornare il firmware. Avviare System Manager e utilizzare Recovery Guru per risolvere il problema.



 a| 
Controller in uno stato diverso da quello ottimale
 a| 
Uno dei controller degli array di storage richiede attenzione. Questa condizione deve essere corretta prima di poter aggiornare il firmware. Avviare System Manager e utilizzare Recovery Guru per risolvere il problema.



 a| 
Informazioni sulla partizione dello storage non corrispondenti tra i grafici a oggetti del controller
 a| 
Si è verificato un errore durante la convalida dei dati sui controller. Contattare il supporto tecnico per risolvere il problema.



 a| 
Controllo SPM Verify Database Controller non riuscito
 a| 
Si è verificato un errore nel database di mappatura delle partizioni di storage su un controller. Contattare il supporto tecnico per risolvere il problema.



 a| 
Configuration Database Validation (convalida del database di configurazione) (se supportata dalla versione del controller dello storage array)
 a| 
Si è verificato un errore del database di configurazione su un controller. Contattare il supporto tecnico per risolvere il problema.



 a| 
Controlli correlati A MEL
 a| 
Contattare il supporto tecnico per risolvere il problema.



 a| 
Negli ultimi 7 giorni sono stati segnalati più di 10 eventi DDE Informational o Critical MEL
 a| 
Contattare il supporto tecnico per risolvere il problema.



 a| 
Negli ultimi 7 giorni sono stati segnalati più di 2 eventi critici MEL di pagina 2C
 a| 
Contattare il supporto tecnico per risolvere il problema.



 a| 
Negli ultimi 7 giorni sono stati segnalati più di 2 eventi MEL critici su Drive Channel degradati
 a| 
Contattare il supporto tecnico per risolvere il problema.



 a| 
Più di 4 voci MEL critiche negli ultimi 7 giorni
 a| 
Contattare il supporto tecnico per risolvere il problema.

|===


.Quali sono le prossime novità?
L'aggiornamento del firmware del disco è stato completato. È possibile riprendere le normali operazioni.
